.\" Manpage for Plugin_rapl
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "18 Feb 2018" "v4" "LDMS Plugin rapl man page"

.SH NAME
Plugin_rapl - man page for the LDMS rapl plugin

.SH SYNOPSIS
Within ldmsd_controller or a configuration file:
.br
config name=rapl [ <attr>=<value> ]

.SH DESCRIPTION
With LDMS (Lightweight Distributed Metric Service), plugins for the ldmsd (ldms daemon) are configured via ldmsd_controller
or a configuration file. The rapl plugin provides energy sampling using RAPL via the PAPI interface for sandybridge.

WARNING: This sampler is unsupported.

.SH CONFIGURATION ATTRIBUTE SYNTAX
The rapl plugin uses the sampler_base base class. This man page covers only the configuration attributes, or those with default values, specific to the this plugin; see ldms_sampler_base.man for the attributes of the base class.



.TP
.BR config
name=<plugin_name> [schema=<sname>]
.br
configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be rapl.
.TP
schema=<schema>
.br
Optional schema name. It is intended that the same sampler on different nodes with different metrics have a
different schema. If not specified, will default to `rapl`.
.RE

.SH BUGS
No known bugs.

.SH NOTES
.PP
.IP \[bu]
WARNING: This is for sandybridge only.
.IP \[bu]
This sampler is unsupported.

.SH EXAMPLES
.PP
Within ldmsd_controller or a configuration file:
.nf
load name=rapl
config name=rapl producer=vm1_1 instance=vm1_1/rapl component_id=1
start name=rapl interval=1000000
.fi

.SH SEE ALSO
ldmsd(8), ldms_quickstart(7), ldmsd_controller(8), ldms_sampler_base(7)
