#!/bin/bash

usage() {
	echo "Usage: ovis-node-services [start|stop|status]"
	echo "	start	Start OVIS daemons (ldmsd_aggregator, Baler, ME, Komondor"
	echo "		and OCMD) on the OVIS head node"
	echo ""
	echo "	stop	Stop the running OVIS daemons on the OVIS head node"
	echo ""
	echo "	status	Return the status of the OVIS services on the OVIS head	node"
}

if [ $# -le 0 ]; then
	usage
	exit -1
fi

cmd=$1

start_head() {
	#ldmsd_aggregator
	echo "ldmsd_aggregator"
	service ldmsd_aggregator start
	echo "------------------------"

	#balerd
	echo "balerd"
	service balerd start
	echo "------------------------"

	#me
	echo "Model Evaluator"
	service me start
	echo "------------------------"

	#komondor
	echo "Corrective Action Engine"
	service komondor start
	echo "------------------------"

	#ocmd
	echo "OVIS Configuration Manager"
	service ocmd start
	echo "------------------------"
}

stop_head() {
	#ldmsd_aggregator
	echo "ldmsd_aggregator"
	service ldmsd_aggregator stop
	echo "------------------------"

	#balerd
	echo "balerd"
	service balerd stop
	echo "------------------------"

	#me
	echo "Model Evaluator"
	service me stop
	echo "------------------------"

	#komondor
	echo "Corrective Action Engine"
	service komondor stop
	echo "------------------------"

	#ocmd
	echo "OVIS Configuration Manager"
	service ocmd stop
	echo "------------------------"
}

check_head() {
	#ldmsd_aggregator
	echo "ldmsd_aggregator"
	service ldmsd_aggregator status
	echo "------------------------"

	#balerd
	echo "balerd"
	service balerd status
	echo "------------------------"

	#me
	echo "Model Evaluator"
	service me status
	echo "------------------------"

	#komondor
	echo "Corrective Action Engine"
	service komondor status
	echo "------------------------"

	#ocmd
	echo "OVIS Configuration Manager"
	service ocmd status
	echo "------------------------"
}

case "$cmd" in
	start)
		start_head
		;;
	stop)
		stop_head
		;;
	status)
		check_head
		;;
	*)
		usage
		exit -1
		;;
esac
