#!/bin/bash

usage() {
	echo "Usage: ovis-services [start|stop|status]"
	echo "	start	Start all OVIS daemons (ldmsd_aggregator, ldmsd_sampler"
	echo "		Baler, ME, Komondor and OCMD) in the cluster"
	echo ""
	echo "	stop	Stop all running OVIS daemons in the cluster"
	echo ""
	echo "	status	Return the status of the OVIS daemons in the cluster"
}

if [ $# -le 0 ]; then
	usage
	exit -1
fi

cmd=$1

case "$cmd" in
	start)
		echo "Starting all ldmsd_samplers"
		ldmsd_sampler_services start
		echo "--------------------------------"
		echo "Starting OVIS services on the OVIS head node"
		ovis_head_services start
		;;
	stop)
		echo "Stopping all ldmsd_samplers"
		ldmsd_sampler_services stop
		echo "--------------------------------"
		echo "Stopping OVIS services on the OVIS head node"
		ovis_head_services stop
		;;
	status)
		echo "Checking the status of all ldmsd_samplers"
		ldmsd_sampler_services status
		echo "--------------------------------"
		echo "Checking the status of the OVIS services on the OVIS head node"
		ovis_head_services status
		;;
	*)
		usage
		exit -1
		;;
esac
