.\" Manpage for Plugin_vmstat
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "04 Dec 2018" "v4" "LDMS Plugin vmstat man page"

.SH NAME
Plugin_vmstat - man page for the LDMS vmstat plugin

.SH SYNOPSIS
Within ldmsd_controller or in a configuration file
.br
config name=vmstat [ <attr>=<value> ]

.SH DESCRIPTION
With LDMS (Lightweight Distributed Metric Service), plugins for the ldmsd (ldms daemon) are configured via ldmsd_controller
or a configuration file. The vmstat plugin provides info from /proc/vmstat.

.SH CONFIGURATION ATTRIBUTE SYNTAX
The vmstat plugin uses the sampler_base base class. This man page covers only the configuration attributes, or those with default values, specific to the this plugin; see ldms_sampler_base.man for the attributes of the base class.

.TP
.BR config
name=<plugin_name> [schema=<sname>]
.br
configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be vmstat.
.TP
schema=<schema>
.br
Optional schema name. It is intended that the same sampler on different nodes with different metrics have a
different schema. If not specified, will default to `vmstat`.
.RE

.SH BUGS
No known bugs.

.SH EXAMPLES
.PP
Within ldmsd_controller or a configuration file:
.nf
load name=vmstat
config name=vmstat producer=1 instance=vm1_1/vmstat
start name=vmstat interval=1000000
.fi

.SH SEE ALSO
ldmsd(8), ldms_quickstart(7), ldmsd_controller(8), ldms_sampler_base(7)
