.\" Manpage for Plugin_meminfo
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "04 Feb 2018" "v4" "LDMS Plugin meminfo man page"

.SH NAME
Plugin_meminfo - man page for the LDMS meminfo plugin

.SH SYNOPSIS
Within ldmsd_controller or a configuration file:
.br
config name=meminfo [ <attr>=<value> ]

.SH DESCRIPTION
With LDMS (Lightweight Distributed Metric Service), plugins for the ldmsd (ldms daemon) are configured via ldmsd_controller
or a configuration file. The meminfo plugin provides memory info from /proc/meminfo.

.SH CONFIGURATION ATTRIBUTE SYNTAX
The meminfo plugin uses the sampler_base base class. This man page covers only the configuration attributes, or those with default values, specific to the this plugin; see ldms_sampler_base.man for the attributes of the base class.



.TP
.BR config
name=<plugin_name> [schema=<sname>]
.br
configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be meminfo.
.TP
schema=<schema>
.br
Optional schema name. It is intended that the same sampler on different nodes with different metrics have a
different schema. If not specified, will default to `meminfo`.
.RE

.SH BUGS
No known bugs.

.SH EXAMPLES
.PP
Within ldmsd_controller or a configuration file:
.nf
load name=meminfo
config name=meminfo producer=vm1_1 instance=vm1_1/meminfo
start name=meminfo interval=1000000
.fi

.SH SEE ALSO
ldmsd(8), ldms_quickstart(7), ldmsd_controller(8), ldms_sampler_base(7)
