.\" Manpage for ldms_auth_none
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "28 Feb 2018" "v4" "ldms_auth_ovis"


.SH NAME
ldms_auth_none \- LDMS authentication disabled 


.SH SYNOPSIS
.HP
.I ldms_app
.BI "-a none [Default]"


.SH DESCRIPTION
.BR ldms_auth_none
enables running without authentication of query sources. Since "-a none"
is the default it need not be specified (e.g., running "ldmsd -x sock:1024 -a none"
is equivalent to simply running "ldmsd -x sock:1024"). Using this authentication 
type there will be NO checks on identities associated with data and/or meta-data
information accesses.

