.\" Manpage for ldms_auth_ovis
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "28 Feb 2018" "v4" "ldms_auth_naive"

.SH NAME
ldms_auth_naive - naive LDMS authentication implementation FOR TESTING


.SH SYNOPSIS
.I ldms_app
.B -a naive
.BI "[-A uid=" UID ]
.BI "[-A gid=" GID ]


.SH DESCRIPTION
.B ldms_auth_naive
LDMS authentication plugin naively believes the peer's credential declaration.
The purpose of this plugin is purely for testing the permission control of
various objects in
.BR ldmsd .
The
.B uid
and
.B gid
options are used to specify the user credential. If
.B uid
and/or
.B gid
are not specified, the default is \-1.
