.\" Manpage for ldms_sampler_base
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "04 Feb 2018" "v4" "LDMS sampler_base  man page"

.SH NAME
sampler_base - man page for the LDMS sampler_base which is the base class for sampler

.SH SYNOPSIS
Configuration variable base class for LDMS samplers.


.SH DESCRIPTION
With LDMS (Lightweight Distributed Metric Service), sampler plugins for the ldmsd (ldms daemon)
should inherit from the sampler_base base class. This class defines variables that should be common to
all samplers. It also adds them to the sampler set set and handles their value assignment.

In order to configure a plugin, one should consult both the plugin specific man page for the
information and configuration arguments specific to the plugin and this man page for the
arguments in the sampler_base.


.SH CONFIGURATION ATTRIBUTE SYNTAX

.TP
.BR config
name=<plugin_name> producer=<name> instance=<name> [component_id=<int>] [schema=<name>] \
	       [job_set=<name> job_id=<name> app_id=<name> job_start=<name> job_end=<name>]

.br
configuration line
.RS
.TP
name=<plugin_name>
.br
This will be the name of the plugin being loaded.
.TP
producer=<pname>
.br
A unique name for the host providing the data.
.TP
instance=<set_name>
.br
A unique name for the metric set.
.TP
schema=<schema>
.br
Optional schema name. It is intended that the same sampler on different nodes with different metrics have a
different schema. Defaults to the sampler name.
.TP
component_id=<compid>
.br
Optional unique number for the component being monitored, Defaults to zero.
.TP
job_set=<name>
.br
The instance name of the set containing the job data, default is 'job_info'.
.TP
job_id=<name>
.br
The name of the metric containing the Job Id, default is 'job_id'.
.TP
app_id=<name>
.br
The name of the metric containing the Application Id, default is 'app_id'.
.TP
job_start=<name>
.br
The name of the metric containing the Job start time, default is 'job_start'.
.TP
job_end=<name>
.br
The name of the metric containing the Job end time, default is 'job_end'.
.RE

.SH NOTES

.PP
.IP \[bu]
This man page does not cover usage of the base class for plugin writers.
.IP \[bu]
Not all plugins may have been converted to use the base class. The plugin specific
man page should refer to the sampler_base where this has occurred.
.PP



.SH BUGS
No known bugs.

.SH EXAMPLES
.PP
Within ldmsd_controller or a configuration file:
.nf
load name=meminfo
config name=meminfo producer=vm1_1 instance=vm1_1/meminfo
start name=meminfo interval=1000000
.fi

.SH SEE ALSO
ldmsd(8), ldms_quickstart(7), ldmsd_controller(8), Plugin_all_example(7), Plugin_aries_linkstatus(7), Plugin_aries_mmr(7), Plugin_array_example(7), Plugin_clock(7), Plugin_cray_sampler_variants(7), Plugin_cray_dvs_sampler(7), Plugin_procdiskstats(7), Plugin_fptrans(7), Plugin_kgnilnd(7), Plugin_lnet_stats(7), Plugin_meminfo(7), Plugin_msr_interlagos(7), Plugin_perfevent(7), Plugin_procinterrupts(7), Plugin_procnetdev(7), Plugin_procnfs(7), Plugin_rapl(7), Plugin_sampler_atasmart(7), Plugin_sysclassib(7), Plugin_synthetic(7), Plugin_vmstat(7)
