.\" Manpage for ldms-plugins.sh
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 8 "28 Feb 2018" "v4" "ldms-plugins.sh man page"

.SH NAME
ldms-plugins.sh \- Display information on installed LDMSD plugins.

.SH SYNOPSIS
ldms-plugins.sh [OPTION] [NAME]

.SH DESCRIPTION
The ldms-plugins.sh command is used to query ldmsd for information on installed
plugins.

.SH OPTIONS
If the NAME is specified, only information for that plugin is displayed.
The names all, store, and sampler are interpreted as described in ldmsd(8).
.TP
-b
.br
Produce brief output, omitting usages.
.TP
-n
.br
Produce names only.

.SH EXAMPLES
.P
ldms-plugins.sh -b
.P
ldms-plugins.sh vmstat
.P
ldms-plugins.sh -n sampler
.P
ldms-plugins.sh -n store

.SH NOTES
Error messages from attempting to load plugins may appear if additionally needed
libraries cannot be found. This is usually a bug in the setting of LD_LIBRARY_PATH.

.SH SEE ALSO
ldmsd(8)
