.\" Manpage for ldmsd_controller
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 8 "19 Nov 2019" "v4.3" "ldmsd_contoller man page"

.SH NAME
ldmsd_controller \- a python program to configure an ldms daemon.

.SH SYNOPSIS
.B ldmsd_controller
[OPTIONS]

ldmsd_controller> <cmd> [ <attr>=<value> ]

.SH DESCRIPTION
With LDMS (Lightweight Distributed Metric Service), the ldmsd
can be configured via the ldmsd_controller.

If ldms is built with --enable-readline, one can invoke the ldmsd_controller
from the command line and obtain an input interface with feedback. In many
instances, instances, however, it is prefered to execute scripts and send the
output commands to an ldmsd instead.

.SH ENVIRONMENT
Note: python2.6 with the additional installation of the argparse module
OR python2.7 (which has the argparse module) is required.

.TP
PYTHONPATH
<path_to_ovis_install>/lib[64]/pythonX.Y/site-packages/
.TP
PATH
<path_to_ovis_install>/bin

.SH LDMSD_CONTROLLER OPTIONS
.TP
.BI -h,--host " HOST"
Hostname of \fBldmsd\fR to connect to
.TP
.BI -p,--port " PORT"
The port of \fBldmsd\fR to connect to
.TP
.BI -x,--xprt " XPRT"
The transport type (\fBsock\fR, \fBrdma\fR, \fBugni\fR).
.TP
.BI -a,--auth " AUTH"
The LDMS authentication plugin. Please see
.BR ldms_authentication (7)
for more information.
.TP
.BI -A,--auth-arg " NAME=VALUE "
Options
.IR NAME = VALUE
Passing the \fINAME\fR=\fIVALUE\fR option to the LDMS Authentication plugin.
This command line option can be given multiple times. Please see
.BR ldms_authentication (7)
for more information, and consult the plugin manual page for plugin-specific
options.
.TP
.BI --source " SOURCE"
.br
Path to the config file
.TP
.BI --script " SCRIPT"
.br
Execute the script and send the output commands to the connected ldmsd
.TP
.BR -?
Display help
.TP
.BR --help
Display help


.SH REGULAR EXPRESSION

The regular expression specified in \fIregex=\fR option of the commands is a
POSIX Extended (modern) Regular Expression. In short, "*+?{}|^$." are special
regular expression characters. Please see \fBregex(7)\fR for more information.


.SH PLUGIN COMMAND SYNTAX

.SS Load a plugin
.BR load
attr=<value>
.br
.RS
.TP
.BI name " name"
.br
The plugin name

.SS List the usage of the loaded plugins
.BR usage

.SS unload a plugin
.BR term
attr=<value>
.br
.RS
.TP
.BI name " name"
.br
The plugin name

.SS Send a configuration command to the specified plugin.
.BR config
attr=<value>
.RS
.TP
.BI name " name"
.br
The plugin name
.TP
.BR attr=value
.br
Plugin specific attr=value tuples

.RS
.B Attributes specific for sampler plugins (Some sampler plugins may have additional
attributes)
.TP
.BI producer " producer"
.br
A unique name for the host providing the data
.TP
.BI instance " instance"
.br
The set instance name. The name must be unique among all metric sets in all LDMS
daemons.
.TP
.BI [component_id " component_id"]
.br
A unique number for the comopnent being monitored. The default is zero.
.TP
.BI [schema " schema"]
.br
The name of the metric set schema.
.TP
.BI [job_set " job_set"]
.br
The set instance name of the set containing the job data. The default is 'job_info'.
.TP
.BI [uid " uid"]
.br
The user id of the set's owner. The default is the returned value of geteuid().
.TP
.BI [gid " gid"]
.br
The group id of the set's owner. The default is the returned value of getegid().
.TP
.BI [perm " perm"]
.br
The sampler plugin instance access permission. The default is 0440.
.RE
.RE

.SS Start a sampler plugin
.BR start
attr=<value>
.RS
.TP
.BI name " name"
.br
The plugin name.
.TP
.BI interval " interval"
.br
The sample interval in microseconds.
.TP
.BI [offset " offset"]
.br
Offset (shift) from the sample mark in microseconds.
Offset can be positive or negative with magnitude up to 1/2
the sample interval. If this offset is specified, including 0,
collection will be synchronous; if the offset is not specified,
collection will be asynchronous. Optional.
.RE


.SS Stop a sampler plugin
.BR stop
attr=<value>
.RS
.TP
.BI name " name"
.br
The plugin name.
.RE

.SH AUTHENTICATION COMMAND SYNTAX
.SS  Add an authentication domain
.B auth_add
\fBname\fR=\fINAME\fR
\fBplugin\fR=\fIPLUGIN\fR
[ ... \fIPLUGIN ATTRIBUTES\fR ... ]
.RS
.TP
\fBname\fR=\fINAME\fR
.br
The name of the authentication domain. This is the name referred to by
\fBlisten\fR and \fBprdcr_add\fR commands.
.TP
\fBplugin\fR=\fInone\fR|\fIovis\fR|\fImunge\fR
.br
The LDMS Authentication Plugin for this domain.
.TP
[ ... \fIPLUGIN ATTRIBUTES\fR ... ]
.br
Arbitrary plugin attributes. Please consult the manual of the authentication
plugin for more information.
.RE


.SH LISTEN COMMAND SYNTAX
.SS  Instruct ldmsd to listen to a port
.B listen
\fBport\fR=\fIPORT\fR
\fBxprt\fR=\fIsock\fR|\fIrdma\fR|\fIugni\fR|\fIfabric\fR
[\fBhost\fR=\fIHOST\fR]
[\fBauth\fR=\fIAUTH_REF\fR]
.RS
.TP
\fBport\fR=\fIPORT\fR
.br
The port to listen to. Also, please be sure not to use ephemeral port (ports in
the range of \fB/proc/sys/net/ip4/ip_local_port_range\fR).
.TP
\fBxprt\fR=\fIsock\fR|\fIrdma\fR|\fIugni\fR|\fIfabric\fR
.br
The type of the transport.
.TP
\fBhost\fR=\fIHOST\fR
.br
An optional hostname or IP address to bind. If not given, listen to all
addresses (0.0.0.0 or PORT).
.TP
\fBauth\fR=\fIAUTH_REF\fR
.br
Instruct \fBldmsd\fR to use \fIAUTH_REF\fR (a name reference to \fBauth\fR
object created by \fBauth_add\fR command) to authenticate connections on this
port. If not given, the port uses the default authentication method specified on
the CLI options (see \fBldmsd\fR(8) option \fB-a\fR).
.RE

.SH PRODUCER COMMAND SYNTAX
.SS  Add a producer to the aggregator
.BR prdcr_add
attr=<value>
.br
.RS
.TP
.BI name " name"
.br
The producer name. The producer name must be unique in an aggregator. It is independent of
any attributes specified for the metric sets or hosts.
.TP
.BI xprt " xprt"
.br
The transport name [sock, rdma, ugni]
.TP
.BI host " host"
.br
The hostname of the host
.TP
.BI type " conn_type"
.br
The connection type [active, passive]
.TP
.BI interval " interval"
.br
The connection retry interval
.TP
.BI [perm " permission"]
.br
The permission to modify the producer in the future
.TP
.BI [auth " AUTH_REF"]
.br
Instruct \fBldmsd\fR to use \fIAUTH_REF\fR (a name reference to \fBauth\fR
object created by \fBauth_add\fR command) with the connections to this
producer. If not given, the default authentication method specified on
the CLI options (see \fBldmsd\fR(8) option \fB-a\fR) is used.
.RE

.SS Delete a producer from the aggregator
The producer cannot be in use or running
.br
.BR prdcr_del
attr=<value>
.RS
.TP
.BI name " name"
.br
The producer name
.RE

.SS Start a producer
.BR prdcr_start
attr=<value>
.RS
.TP
.BI name " name"
.br
The producer name
.TP
.BI [interval " interval"]
.br
The connection retry interval in microsec. If unspecified,
the previously configured value will be used. Optional.
.RE

.SS Start all producers matching a regular expression
.BR prdcr_start_regex
attr=<value>
.RS
.TP
.BI regex " regex"
.br
A regular expression
.TP
.BI [interval " interval"]
.br
The connection retry interval in microsec. If unspecified,
the previously configured value will be used. Optional.
.RE

.SS Stop a producer
.BR prdcr_stop
attr=<value>
.RS
.TP
.BI name " name"
.br
The producer name
.RE

.SS Stop all producers matching a regular expression
.BR prdcr_stop_regex
attr=<value>
.RS
.TP
.BI regex " regex"
.br
A regular expression
.RE

.SS Query producer status
.BR prdcr_status
attr=<value>
.RS
.TP
.BI [name " name"]
.br
The producer name. If none is given, the statuses of all producers are
reported.
.RE

.SS Subscribe for stream data from all matching producers
.BR prdcr_subsribe
.RS
.TP
.BI regex " regex"
.br
The regular expression matching producer name
.TP
.BI stream " stream"
.br
The stream name
.RE

.SH UPDATER COMMAND SYNTAX
.SS Add an updater process that will periodically sample producer metric sets
.BR updtr_add
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name. The policy name should be unique. It is independent of
any attributes specified for the metric sets or hosts.
.TP
.BI interval " interval"
.br
The update/collect interval
.TP
.BI [offset " offset"]
.br
Offset for synchronized aggregation. Optional.
.TP
.BI [push " onchange|true" ]
.br
Push mode: 'onchange' and 'true'. 'onchange' means the Updater will get an
update whenever the set source ends a transaction or pushes the update. 'true'
means the Updater will receive an update only when the set source pushes the
update. If `push` is used, `auto_interval` cannot be `true`.
.TP
.BI [auto_interval " true|false "]
If true, the updater will schedule set updates according to the update hint. The
sets with no hints will not be updated. If false, the updater will schedule the
set updates according to the given interval and offset values. If not specified,
the value is \fIfalse\fR.
.TP
.BI [perm " permission"]
.br
The permission to modify the updater in the future
.RE

.SS Remove an updater from the configuration
.BR updtr_del
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.RE

.SS Add a match condition that specifies the sets to update.
.BR updtr_match_add
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.TP
.BI regex " regex"
.br
The regular expression
.TP
.BI match " match (inst|schema)"
.br
The value with which to compare; if match=inst,
the expression will match the set's instance name, if
match=schema, the expression will match the set's
schema name.
.RE

.SS Remove a match condition from the Updater.
.BR updtr_match_del
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.TP
.BI regex " regex"
.br
The regular expression
.TP
.BI match " match (inst|schema)"
.br
The value with which to compare; if match=inst,
the expression will match the set's instance name, if
match=schema, the expression will match the set's
schema name.
.RE

.SS Add matching producers to an updater policy
This is required before starting the updater.

.BR updtr_prdcr_add
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.TP
.BI regex " regex"
.br
A regular expression matching zero or more producers
.RE

.SS Remove matching producers to an updater policy
.BR updtr_prdcr_del
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.TP
.BI regex " regex"
.br
A regular expression matching zero or more producers
.RE

.SS Start updaters.
.BR updtr_start
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.TP
.BI [interval " interval"]
.br
The update interval in micro-seconds. If this is not
specified, the previously configured value will be used. Optional.
.TP
.BI [offset " offset"]
.br
Offset for synchronized aggregation. Optional.
.RE

.SS Stop an updater.
The Updater must be stopped in order to change it's configuration.

.BR updtr_stop
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.RE

.SS Query the updater status
.BR updtr_status
attr=<value>
.RS
.TP
.BI [name " name"]
.br
The updater name. If none is given, the statuses of all updaters are
reported.
.RE

.SH STORE COMMAND SYNTAX
.SS Create a Storage Policy and open/create the storage instance.
.BR strgp_add
attr=<value>
.RS
.TP
.BI name " name"
.br
The unique storage policy name.
.TP
.BI plugin " plugin"
.br
The name of the storage backend.
.TP
.BI container " container"
.br
The storage backend container name.
.TP
.BI schema " schema"
.br
The schema name of the metric set to store.
.TP
.BI [perm " permission"]
.br
The permission to modify the storage in the future
.RE

.SS Remove a Storage Policy
All updaters must be stopped in order for a storage policy to be deleted
.br
.BR strgp_del
attr=<value>
.RS
.TP
.BI name " name"
.br
The storage policy name
.RE

.SS Add a regular expression used to identify the producers this storage policy will apply to.
If no producers are added to the storage policy, the storage policy will apply
on all producers.
.br
.BR strgp_prdcr_add
attr=<value>
.RS
.TP
.BI name " name"
.br
The storage policy name
.TP
.BI regex " name"
.br
A regular expression matching metric set producers.
.RE


.SS Remove a regular expression from the producer match list
.BR strgp_prdcr_del
attr=<value>
.RS
.BI name " name"
.br
The storage policy name
.TP
.BI regex " regex"
.br
The regex of the producer to remove.
.RE


.SS Add the name of a metric to store
.BR strgp_metric_add
attr=<value>
.RS
.BI name " name"
.br
The storage policy name
.TP
.BI metric " metric"
.br
The metric name. If the metric list is NULL, all metrics in the metric set will be stored.
.RE

.SS Remove a metric from the set of stored metrics.
.BR strgp_metric_del
attr=<value>
.RS
.BI name " name"
.br
The storage policy name
.TP
.BI metric " metric"
.br
The metric to remove
.RE

.SS Start a storage policy.
.BR strgp_start
attr=<value>
.RS
.BI name " name"
.br
The storage policy name
.RE


.SS Stop a storage policy.
A storage policy must be stopped in order to change its configuration.

.BR strgp_stop
attr=<value>
.RS
.BI name " name"
.br
The storage policy name
.RE

.SS Query the storage policy status
.BR strgp_status
attr=<value>
.RS
.TP
.BI [name " name"]
.br
The storage policy name. If none is given, the statuses of all storage policies
are reported.
.RE

.SH FAILOVER COMMAND SYNTAX

Please see \fBldmsd_failover\fR(7).


.SH SETGROUP COMMAND SYNTAX

Please see \fBldmsd_setgroup\fR(7).

.SH STREAM COMMAND SYNTAX
.SS Publish data to the named stream
.BR plublish
attr=<value>
.RS
.TP
.BI name " name"
.br
The stream name
.TP
.BI data " data"
.br
The data to publish
.RE

.SS Subscribe to a stream
.BR subscribe
attr=<value>
.RS
.TP
.BI name " name"
.br
The stream name
.RE

.SH LDMS DAEMON COMMAND SYNTAX
.SS Changing the verbosity level of ldmsd
.BR loglevel
attr=<value>
.RS
.BI level " level"
.br
Verbosity levels [DEBUG, INFO, ERROR, CRITICAL, QUIET]
.RE

.SS Exit the connected LDMS daemon gracefully
.BR daemon_exit

.SS Query the connected LDMS daemon status
.BR daemon_status


.SS Tell the daemon to dump it's internal state to the log file.
.BR status
<type> [name=<value>]
.RS
.BI [ type]
.br
Reports only the specified objects. The choices are prdcr, updtr and strgp.
.RS
prdcr: list the state of all producers.
.br
updtr: list the state of all update policies.
.br
strgp: list the state of all storage policies.
.RE
.TP
.RI [name " value"]
The object name of which the status will be reported.
.RE

.SH MISC COMMAND SYNTAX

.SS Display the list of available commands
.br
.BR help
<command>
.RS
.RI [ command]
.br
If a command is given, the help of the command will be printed. Otherwise, only
the available command names are printed.
.RE

.SS Set the user data value for a metric in a metric set.
.br
.BR udata
attr=<value>
.RS
.TP
.BI set " set"
.br
The sampler plugin name
.TP
.BI metric " metric"
.br
The metric name
.TP
.BI udata " udata"
.br
The desired user-data. This is a 64b unsigned integer.
.RE

.SS Set the user data of multiple metrics using regular expression.
The user data of the first matched metric is set to the base value.
The base value is incremented by the given 'incr' value and then
sets to the user data of the consecutive matched metric and so on.
.br
.BR udata_regex
attr=<value>
.RS
.TP
.BI set " set"
.br
The metric set name.
.TP
.BI regex " regex"
.br
A regular expression to match metric names to be set
.TP
.BI base " base"
.br
The base value of user data (uint64)
.TP
.BI [incr " incr"]
.br
Increment value (int). The default is 0. If incr is 0,
the user data of all matched metrics are set
to the base value. Optional.

.SS Get the LDMS version the running LDMSD is based on.
.BR version

.SS Launch a subshell to do arbitrary commands
.BR ! shell-command

.SS Comment (a skipped line)
.BR # comment-string

.SH BUGS
No known bugs.

.SH EXAMPLES
.SS
Example of a script to add producers to updaters
.nf
> more add_prdcr.sh
#!/bin/bash

SOCKDIR=/XXX/run/ldmsd
portbase=61100
port1=`expr $portbase + 1`
port2=`expr $portbase + 2`
port3=`expr $portbase + 3`

echo "prdcr_add name=localhost2 host=localhost type=active xprt=sock port=$port2 interval=20000000"
echo "prdcr_start name=localhost2"
echo "prdcr_add name=localhost1 host=localhost type=active xprt=sock port=$port1 interval=20000000"
echo "prdcr_start name=localhost1"
echo "updtr_add name=policy5_h1 interval=2000000 offset=0"
echo "updtr_prdcr_add name=policy5_h1 regex=localhost1"
echo "updtr_start name=policy5_h1"
echo "updtr_add name=policy5_h2 interval=5000000 offset=0"
echo "updtr_prdcr_add name=policy5_h2 regex=localhost2"
echo "updtr_start name=policy5_h2"
.fi

.SS
Example of a script to add and start stores
.nf
> more add_store.sh
#!/bin/bash

# whole path must exist
STORE_PATH=/XXX/ldmstest/store
mkdir -p $STORE_PATH
sleep 1

# CSV
echo "load name=store_csv"
echo "config name=store_csv path=$STORE_PATH action=init altheader=0 rollover=30 rolltype=1"
echo "config name=store_csv action=custom container=csv schema=cray_aries_r altheader=1  userdata=0"

echo "strgp_add name=policy_mem plugin=store_csv container=csv schema=meminfo"
echo "strgp_start name=policy_mem"

#echo "strgp_add name=csv_memfoo_policy plugin=store_csv container=meminfo schema=meminfo_foo"
#echo "strgp_prdcr_add name=csv_memfoo_policy regex=localhost*"
#echo "strgp_start name=csv_memfoo_policy"
.fi

.SS
Example to start an ldmsd and use ldmsd_controller to call a script
.nf
> ldmsd -x sock:11111 -l log.txt
> ldmsd_controller --host localhost --port 11111 --xprt sock --script myscript.sh
.fi

.SH SEE ALSO
ldmsd(8), ldmsctl(8), ldms_quickstart(7), ldmsd_failover(7), ldmsd_setgroup(7)
