.\" Manpage for ldmsd ldms-aggd
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 8 "28 Feb 2018" "v4" "ldmsd man page"

.SH NAME
ldmsd \- Start an ldms daemon

.SH SYNOPSIS
ldmsd [OPTION...]

.SH DESCRIPTION
The ldmsd command can be used
to start an ldms daemon. Plugin configuration of the ldmsd can be done via the
a configuration file or the ldmsd_controller.

Starting ldmsd with the configuration file option enables you to statically configure a
sampler without requiring python. Dynamically configuring samplers with ldmsd_controller requires python.
Currently, v2's ldmsctl can still be used to dynamically configure a sampler without requiring
python. This capability will be replaced and it is not recommended that you use this option.

.SH ENVIRONMENT
.SS
The following environment variables must usually be set:
.TP
LD_LIBRARY_PATH
Path to ovis/lib and libevent2/lib, if not in a system default path. Depending on the system these may be lib64 instead of lib.
.TP
PATH
Include the path to sbin directory containing ldmsd.
.SS The following environment variables may be set to override compiled-in defaults:
.TP
ZAP_LIBPATH
Path to ovis/lib/ovis-ldms
.TP
LDMSD_PLUGIN_LIBPATH
Path to ovis/lib/ovis-ldms
.TP
LDMSD_PIDFILE
Full path name of pidfile overriding the default /var/run/ldmsd.pid unless the command line argument "-r pidfilepath" is present.
.TP
LDMSD_SOCKPATH
Path to the unix domain socket for the ldmsd. Default is created within /var/run. If you must change the default (e.g., not running as root and hence /var/run is not writeable), set this variable (e.g., /tmp/run/ldmsd) or specify "-S socketpath" to ldmsd.
.TP
LDMSD_MEM_SZ
The size of memory reserved for metric sets. Set this variable or specify "-m"
to ldmsd. See the -m option for further details. If both are specified, the -m
option takes precedence over this environment variable.

.SS CRAY Specific Environment variables for ugni transport
ZAP_UGNI_PTAG
For XE/XK, the PTag value as given by apstat -P.
For XC, The value does not matter but the environment variable must be set.
.TP
ZAP_UGNI_COOKIE
For XE/XK, the Cookie value corresponding to the PTag value as given by apstat -P
For XC, the Cookie value (not Cookie2) as given by apstat -P
.TP
ZAP_UGNI_CQ_DEPTH
Optional value for the CQ depth. Default is 2048.
.TP
ZAP_UGNI_STATE_INTERVAL
Optional. If set, then ldmsd will check all nodes' states via rca interface.
States for all nodes are checked and stored at intervals determined by this environment variable. The stored
values are checked against before contacting a node. If you choose to use this option, then the rule of
thumb is to set ZAP_UGNI_STATE_INTERVAL and ZAP_UGNI_STATE_OFFSET such that the node states are checked
before the metric set update occurs (see interval and offset in ldmsd_controller)
.TP
ZAP_UGNI_STATE_OFFSET
Optional. Only relevant if ZAP_UGNI_STATE_INTERVAL is set. Defaults to zero. Offset from zero for
checking the nodes state (see ZAP_UGNI_STATE_INTERVAL, above).


.SH OPTIONS
.SS
General/Configuration Options:
.TP
.BR -F
Run in foreground mode; don't daemonize the program. Default is false.
.TP
.BR -B version-file-mode
When run in daemon mode, controls the existence of the banner file.
Mode 0 suppresses the version file. Mode 1 deletes it at daemon exit. Mode >= 2 leaves it in place for debugging after daemon exit. Default mode is 1.
The banner contains the software and protocol versions information, which is also logged at the INFO level. The banner file name is always the pidfile name with .version appended.
.TP
.BR -c
The path to configuration file (optional, default: <none>).
.TP
.BI -m " MEMORY_SIZE"
.br
MEMORY_SIZE is the maximum size of pre-allocated memory for metric sets.
The given size must be less than 1 petabytes.
For example, 20M or 20mb are 20 megabytes. The default is adequate for most ldmsd acting in the collector role.
For aggregating ldmsd, a rough estimate of preallocated memory needed is (Number of nodes aggregated) x (Number of metric sets per node) x 4k.
Data sets containing arrays may require more.
.TP
.BI -r " pid_file"
The path to the pid file and prefix of the .version banner file for daemon mode.
.TP
.BR -V
Display LDMS version information and then exit.
.TP
.BR -u " plugin_name"
Display the usage for named plugin. Special names all, sampler, and store match all, sampler type, and store type plugins, respectively.


.SS
Communication Options:
.TP
.BI -x " XPRT" [: PORT ]
.br
Specifies the transport type to listen on. May be specified more than once for
multiple transports. The XPRT string is one of 'rdma', 'sock', or 'ugni' (CRAY
XE/XK/XC).  A transport specific port number is optionally specified following a
\':', e.g. rdma:10000.
.TP
.BI -a " AUTH"
AUTH is the name of the LDMS Authentication plugin to be used for the
LDMS connection. Please see
.BR ldms_authentication (7)
for more information. If this option is not given, the default is "none" (no
authentication).
.TP
.BI -A " NAME" = VALUE
Passing the \fINAME\fR=\fIVALUE\fR option to the LDMS Authentication plugin.
This command line option can be given multiple times. Please see
.BR ldms_authentication (7)
for more information, and consult the plugin manual page for plugin-specific
options.


.SS
Log Verbosity Options:
.TP
.BI -l " LOGFILE"
.br
LOGFILE is the path to the log file for status messages. Default is stdout unless given.
The syslog facility is used if LOGFILE is exactly "syslog".
Silence can be obtained by specifying /dev/null for the log file or using command line redirection as illustrated below.
.TP
.BI -v " LOG_LEVEL"
.br
LOG_LEVEL can be one of DEBUG, INFO, ERROR, CRITICAL or QUIET.
The default level is ERROR. QUIET produces only user-requested output.
(Note: this has changed from the previous release where q designated no (QUIET) logging).

.SS
Kernel Metric Options:
.TP
.BR -k
Publish kernel metrics.
.TP
.BI -s " SETFILE"
Text file containing kernel metric sets to publish. Default: /proc/sys/kldms/set_list

.SS Thread Options:
.TP
.BI -P " THR_COUNT"
.br
THR_COUNT is the number of event threads to start.
.TP
.BI -f " COUNT"
.br
COUNT is the number of flush threads.
.TP
.BI -D " NUM"
.br
NUM is the number of bytes of the dirty threshold used for store rollover.

.SS Test Options:
.TP
.BI -H " host_name"
.br
The host/producer name for test metric sets
.TP
.BI -i " interval"
.br
Test metric set sample interval
.TP
.BI -t " count"
.br
Create set_count instances of set_name.
.TP
.BI -T " set_name"
.br
Test set prefix
.TP
.BR -N
.br
Notify registered monitors of the test metric sets.

.SS Obsolete options:
.TP
.BI "-q -Z -z -S"
.br
These v2 options are no longer supported, and will cause exit with a hint.

.TP
.BI -p " XPRT" : (NAME|PORT)
The configuration-only transports have been removed from \fBldmsd\fR v4 to
leverage the pluggable authentication capability in LDMS transport.

.SH RUNNING LDMSD ON CRAY XE/XK/XC SYSTEMS USING APRUN
.PP
ldsmd can be run as either a user or as root using the appropriate PTag and cookie.
.PP
Check (or set) the PTag and cookie.
.RS
Cray XE/XK Systems:
.nf
> apstat -P
PDomainID           Type    Uid   PTag     Cookie
LDMS              system      0     84 0xa9380000
foo               user    22398    243  0x2bb0000

Cray XC Systems:
> apstat -P
PDomainID   Type   Uid     Cookie    Cookie2
LDMS      system     0 0x86b80000          0
foo         user 20596 0x86bb0000 0x86bc0000
.RE
.fi
.PP
Set the environment variables ZAP_UGNI_PTAG and ZAP_UGNI_COOKIE with the appropriate ptag and cookie.
.PP
Run ldmsd directly or as part of a script launched from aprun. In either case, Use aprun with the correct -p <ptag> when running.

.SH NOTES
OCM flags are unsupported at this time.

.SH BUGS
None known.

.SH EXAMPLES
.PP
.nf
$/tmp/opt/ovis/sbin/ldmsd -x sock:60000 -p unix:/var/run/ldmsd/metric_socket -l /tmp/opt/ovis/logs/1
.br
$/tmp/opt/ovis/sbin/ldmsd -x sock:60000 -p sock:61000 -p unix:/var/runldmsd/metric_socket
.fi


.SH SEE ALSO
ldms_authentication(7), ldmsctl(8), ldms_ls(8), ldmsd_controller(8), ldms_quickstart(7)
