\" Manpage for ldmsctl
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 8 "19 Nov 2019" "v4.3" "ldmsctl man page"

.SH NAME
ldmsctl \- Issue control commands to ldmsd.

.SH SYNOPSIS
ldmsctl [OPTION...]

.SH DESCRIPTION
After LDMS (lightweight Distributed Metric Service) version 3.4, ldmsctl is an
LDMS daemon C-interface that can be used to dynamically configure an LDMS daemon
instead of ldmsd_controller when Python is not available. After the ldmsctl is
started commands can be entered at the prompt or (usually) a command script can
be created and piped into the ldmsctl.

LDMS version 4 requires ldmsctl to use LDMS transport (data channel) to connect
to \fBldmsd\fR to levarage LDMS Authentication plugin in the transport. Please
note that the \fBldmsd\fR may have multiple data channels, one of which can be
dedicated for management use.

.SH ENVIRONMENT
The following environment variables must be set (includes environment variables needed for the actions,
for example, paths to the sampler libraries to be added):
.TP
LD_LIBRARY_PATH
path_to_ovis_build/lib:path_to_ovis_build/lib/ovis-ldms:path_to_libevent_2.0_build/lib
.TP
ZAP_LIBPATH
path_to_ovis_build/lib/ovis-ldms
.TP
LDMSD_PLUGIN_LIBPATH
path_to_ovis_build/lib/ovis-ldms
.TP
PATH
path_to_ovis_build/sbin:path_to_ovis_build/bin


.SH OPTIONS
.TP
.BI -h " HOST"
HOST is the hostname to connect to the LDMS daemon
.TP
.BI -p " PORT"
PORT is the port to connect to the LDMS daemon
.TP
.BI -x " XPRT"
XPRT is the transport one of sock, ugni, or rdma. Only use with the option -i
.TP
.BI -a " AUTH"
AUTH is the name of the LDMS Authentication plugin to be used for the
connection. Please see
.BR ldms_authentication (7)
for more information. If this option is not given, the default is "none" (no
authentication).
.TP
.BI -A " NAME" = VALUE
Passing the \fINAME\fR=\fIVALUE\fR option to the LDMS Authentication plugin.
This command line option can be given multiple times. Please see
.BR ldms_authentication (7)
for more information, and consult the plugin manual page for plugin-specific
options.
.TP
.BI -s " SOURCE"
SOURCE is the path to a configuration file
.TP
.BI -X " COMMAND"
COMMAND is a shell command to be executed. The output will be sent to ldmsd.
.TP
.BR -V
Display LDMS version information and then exit.


.SH REGULAR EXPRESSION

The regular expression specified in \fIregex=\fR option of the commands is a
POSIX Extended (modern) Regular Expression. In short, "*+?{}|^$." are special
regular expression characters. Please see \fBregex(7)\fR for more information.

.SH PLUGIN COMMAND SYNTAX

.SS Load a plugin
.BR load
attr=<value>
.br
.RS
.TP
.BI name " name"
.br
The plugin name

.SS List the usage of the loaded plugins
.BR usage

.SS unload a plugin
.BR term
attr=<value>
.br
.RS
.TP
.BI name " name"
.br
The plugin name

.SS Send a configuration command to the specified plugin.
.BR config
attr=<value>
.RS
.TP
.BI name " name"
.br
The plugin name
.TP
.BR attr=value
.br
Plugin specific attr=value tuples

.RS
.B Attributes specific for sampler plugins (Some sampler plugins may have additional
attributes)
.TP
.BI producer " producer"
.br
A unique name for the host providing the data
.TP
.BI instance " instance"
.br
The set instance name. The name must be unique among all metric sets in all LDMS
daemons.
.TP
.BI [component_id " component_id"]
.br
A unique number for the comopnent being monitored. The default is zero.
.TP
.BI [schema " schema"]
.br
The name of the metric set schema.
.TP
.BI [job_set " job_set"]
.br
The set instance name of the set containing the job data. The default is 'job_info'.
.TP
.BI [uid " uid"]
.br
The user id of the set's owner. The default is the returned value of geteuid().
.TP
.BI [gid " gid"]
.br
The group id of the set's owner. The default is the returned value of getegid().
.TP
.BI [perm " perm"]
.br
The sampler plugin instance access permission. The default is 0440.
.RE
.RE

.SS Start a sampler plugin
.BR start
attr=<value>
.RS
.TP
.BI name " name"
.br
The plugin name.
.TP
.BI interval " interval"
.br
The sample interval, which is a float followed by a unit string.
If no unit string is given, the default unit is microseconds.
A unit string is one of the followings:
  us -- microseconds
  ms -- milliseconds
  s  -- seconds
  m  -- minutes
  h  -- hours
  d  -- days
.TP
.BI [offset " offset"]
.br
Offset (shift) from the sample mark. The value is an integer,
followed by a unit string.
Offset can be positive or negative with magnitude up to 1/2
the sample interval. If this offset is specified, including 0,
collection will be synchronous; if the offset is not specified,
collection will be asynchronous. Optional.
.RE

.SS Stop a sampler plugin
.BR stop
attr=<value>
.RS
.TP
.BI name " name"
.br
The plugin name.
.RE


.SH PRODUCER COMMAND SYNTAX
.SS  Add a producer to the aggregator
.BR prdcr_add
attr=<value>
.br
.RS
.TP
.BI name " name"
.br
The producer name. The producer name must be unique in an aggregator. It is independent of
any attributes specified for the metric sets or hosts.
.TP
.BI xprt " xprt"
.br
The transport name [sock, rdma, ugni]
.TP
.BI host " host"
.br
The hostname of the host
.TP
.BI type " conn_type"
.br
The connection type [active, passive]
.TP
.BI reconnect " interval"
.br
The connection retry interval, which is a float followed by a unit string.
If no unit string is given, the default unit is microseconds.
A unit string is one of the followings:
  us -- microseconds
  ms -- milliseconds
  s  -- seconds
  m  -- minutes
  h  -- hours
  d  -- days
.TP
.BI interval " interval"
.br
It is being precated. Please use 'reconnect'.
.TP
.BI [perm " permission"]
.br
The permission to modify the producer in the future
.RE

.SS Delete a producer from the aggregator
The producer cannot be in use or running
.br
.BR prdcr_del
attr=<value>
.RS
.TP
.BI name " name"
.br
The producer name
.RE

.SS Start a producer
.BR prdcr_start
attr=<value>
.RS
.TP
.BI name " name"
.br
The producer name
.TP
.BI [reconnect " interval"]
.br
The connection retry interval, which is a float followed by a unit string.
If no unit string is given, the default unit is microseconds.
A unit string is one of the followings:
  us -- microseconds
  ms -- milliseconds
  s  -- seconds
  m  -- minutes
  h  -- hours
  d  -- days
If unspecified, the previously configured value will be used. Optional.
.TP
.BI [interval " interval"]
.br
It is being deprecated. Please use 'reconnect'.
.RE

.SS Start all producers matching a regular expression
.BR prdcr_start_regex
attr=<value>
.RS
.TP
.BI regex " regex"
.br
A regular expression
.TP
.BI [reconnect " interval"]
.br
The connection retry interval, which is a float followed by a unit string.
If no unit string is given, the default unit is microseconds.
A unit string is one of the followings:
  us -- microseconds
  ms -- milliseconds
  s  -- seconds
  m  -- minutes
  h  -- hours
  d  -- days
If unspecified, the previously configured value will be used. Optional.
.TP
.BI [interval " interval"]
.br
It is being deprecated. Please use 'reconnect'.
.RE

.SS Stop a producer
.BR prdcr_stop
attr=<value>
.RS
.TP
.BI name " name"
.br
The producer name
.RE

.SS Stop all producers matching a regular expression
.BR prdcr_stop_regex
attr=<value>
.RS
.TP
.BI regex " regex"
.br
A regular expression
.RE

.SS Query producer status
.BR prdcr_status
attr=<value>
.RS
.TP
.BI [name " name"]
.br
The producer name. If none is given, the statuses of all producers are
reported.
.RE

.SS Subscribe for stream data from all matching producers
.BR prdcr_subsribe
.RS
.TP
.BI regex " regex"
.br
The regular expression matching producer name
.TP
.BI stream " stream"
.br
The stream name
.RE


.SH UPDATER COMMAND SYNTAX
.SS Add an updater process that will periodically sample producer metric sets
.BR updtr_add
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name. The policy name should be unique. It is independent of
any attributes specified for the metric sets or hosts.
.TP
.BI interval " interval"
.br
The update/collect interval, which is a float followed by a unit string.
If no unit string is given, the default unit is microseconds.
A unit string is one of the followings:
  us -- microseconds
  ms -- milliseconds
  s  -- seconds
  m  -- minutes
  h  -- hours
  d  -- days
.TP
.BI [offset " offset"]
.br
Offset for synchronized aggregation. Optional.
.TP
.BI [push " onchange|true" ]
.br
Push mode: 'onchange' and 'true'. 'onchange' means the Updater will get an
update whenever the set source ends a transaction or pushes the update. 'true'
means the Updater will receive an update only when the set source pushes the
update. If `push` is used, `auto_interval` cannot be `true`.
.TP
.BI [auto_interval " true|false "]
If true, the updater will schedule set updates according to the update hint. The
sets with no hints will not be updated. If false, the updater will schedule the
set updates according to the given interval and offset values. If not specified,
the value is \fIfalse\fR.
.TP
.BI [perm " permission"]
.br
The permission to modify the updater in the future
.RE

.SS Remove an updater from the configuration
.BR updtr_del
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.RE

.SS Add a match condition that specifies the sets to update.
.BR updtr_match_add
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.TP
.BI regex " regex"
.br
The regular expression
.TP
.BI match " match (inst|schema)"
.br
The value with which to compare; if match=inst,
the expression will match the set's instance name, if
match=schema, the expression will match the set's
schema name.
.RE

.SS Remove a match condition from the Updater.
.BR updtr_match_del
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.TP
.BI regex " regex"
.br
The regular expression
.TP
.BI match " match (inst|schema)"
.br
The value with which to compare; if match=inst,
the expression will match the set's instance name, if
match=schema, the expression will match the set's
schema name.
.RE

.SS Add matching producers to an updater policy
This is required before starting the updater.

.BR updtr_prdcr_add
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.TP
.BI regex " regex"
.br
A regular expression matching zero or more producers
.RE

.SS Remove matching producers to an updater policy
.BR updtr_prdcr_del
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.TP
.BI regex " regex"
.br
A regular expression matching zero or more producers
.RE

.SS Start updaters.
.BR updtr_start
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.TP
.BI [interval " interval"]
.br
The update interval, which is a float followed by a unit string.
If no unit string is given, the default unit is microseconds.
A unit string is one of the followings:
  us -- microseconds
  ms -- milliseconds
  s  -- seconds
  m  -- minutes
  h  -- hours
  d  -- days
If this is not specified, the previously configured value will be used. Optional.
.TP
.BI [offset " offset"]
.br
Offset for synchronized aggregation. Optional.
.RE

.SS Stop an updater.
The Updater must be stopped in order to change it's configuration.

.BR updtr_stop
attr=<value>
.RS
.TP
.BI name " name"
.br
The update policy name
.RE

.SS Query the updater status
.BR updtr_status
attr=<value>
.RS
.TP
.BI [name " name"]
.br
The updater name. If none is given, the statuses of all updaters are
reported.
.RE

.SS Query updaters' list of regular expressions to match set names and set schemas
.BR updtr_match_list
attr=<value>
.RS
.TP
.BI [name " name"]
.br
The updater name. If none is given, all updaters' regular expressions list are returned.
.RE

.SH STORE COMMAND SYNTAX
.SS Create a Storage Policy and open/create the storage instance.
.BR strgp_add
attr=<value>
.RS
.TP
.BI name " name"
.br
The unique storage policy name.
.TP
.BI plugin " plugin"
.br
The name of the storage backend.
.TP
.BI container " container"
.br
The storage backend container name.
.TP
.BI [schema " schema"]
.br
The schema name of the metric set to store. If 'schema' is given, 'regex' is ignored. Either 'schema' or 'regex' must be given.
.TP
.BI [regex "name"]
.br
A regular expression matching set schemas. It must be used with decomposition. Either 'schema' or 'regex' must be given.
.TP
.BI [perm " permission"]
.br
The permission to modify the storage in the future
.RE

.SS Remove a Storage Policy
All updaters must be stopped in order for a storage policy to be deleted
.br
.BR strgp_del
attr=<value>
.RS
.TP
.BI name " name"
.br
The storage policy name
.RE

.SS Add a regular expression used to identify the producers this storage policy will apply to.
If no producers are added to the storage policy, the storage policy will apply
on all producers.
.br
.BR strgp_prdcr_add
attr=<value>
.RS
.TP
.BI name " name"
.br
The storage policy name
.TP
.BI regex " name"
.br
A regular expression matching metric set producers.
.RE


.SS Remove a regular expression from the producer match list
.BR strgp_prdcr_del
attr=<value>
.RS
.BI name " name"
.br
The storage policy name
.TP
.BI regex " regex"
.br
The regex of the producer to remove.
.RE


.SS Add the name of a metric to store
.BR strgp_metric_add
attr=<value>
.RS
.BI name " name"
.br
The storage policy name
.TP
.BI metric " metric"
.br
The metric name. If the metric list is NULL, all metrics in the metric set will be stored.
.RE

.SS Remove a metric from the set of stored metrics.
.BR strgp_metric_del
attr=<value>
.RS
.BI name " name"
.br
The storage policy name
.TP
.BI metric " metric"
.br
The metric to remove
.RE

.SS Start a storage policy.
.BR strgp_start
attr=<value>
.RS
.BI name " name"
.br
The storage policy name
.RE


.SS Stop a storage policy.
A storage policy must be stopped in order to change its configuration.

.BR strgp_stop
attr=<value>
.RS
.BI name " name"
.br
The storage policy name
.RE

.SS Query the storage policy status
.BR strgp_status
attr=<value>
.RS
.TP
.BI [name " name"]
.br
The storage policy name. If none is given, the statuses of all storage policies
are reported.
.RE

.SH FAILOVER COMMAND SYNTAX

Please see \fBldmsd_failover\fR(7).


.SH SETGROUP COMMAND SYNTAX

Please see \fBldmsd_setgroup\fR(7).

.SH STREAM COMMAND SYNTAX
.SS Publish data to the named stream
.BR plublish
attr=<value>
.RS
.TP
.BI name " name"
.br
The stream name
.TP
.BI data " data"
.br
The data to publish
.RE

.SS Subscribe to a stream
.BR subscribe
attr=<value>
.RS
.TP
.BI name " name"
.br
The stream name
.RE

.SH LDMS DAEMON COMMAND SYNTAX
.SS Changing the log levels of LDMSD infrastructures
.BR loglevel
attr=<value> (deprecated)

.BR log_level
attr=<value>
.TP
.BI level " string"
.br
A string specifying the log levels to be enabled

The valid string are "default", "quiet", and a comma-separated list of DEBUG, INFO, WARN, ERROR, and CRITICAL. It is case insensitive. "default" means to set the log level to the defaul log level. "quiet" means disable the log messages. We note that "<level>," and "<level>" give different results. "<level>" -- a single level name -- sets the log level to the given level and all the higher severity levels. In contrast, "<level>," -- a level name followed by a comma -- sets the log level to only the given level.
.TP
.BI [name " name"]
.br
A logger name
.TP
.BI [regex " regex"]
.br
A regular expression matching logger names. If neither 'name' or 'regex' is given, the command sets the default log level to the given level. For example, 'regex=xprt.*' will change the transport-related log levels. Use log_status to query the available log infrastructures.
.RE

.SS Query LDMSD's log information
.BR log_status
attr=<value>
.RS
.BI [name " value"]
.br
A logger name
.RE

.SS Exit the connected LDMS daemon gracefully
.BR daemon_exit

.SS Query the connected LDMS daemon status
.BR daemon_status

.SS Tell the daemon to dump it's internal state to the log file.
.BR status
<type> [name=<value>]
.RS
.BI [ type]
.br
Reports only the specified objects. The choices are prdcr, updtr and strgp.
.RS
prdcr: list the state of all producers.
.br
updtr: list the state of all update policies.
.br
strgp: list the state of all storage policies.
.RE
.TP
.RI [name " value"]
The object name of which the status will be reported.
.RE

.SH SET COMMAND SYNTAX

.SS Set the user data value for a metric in a metric set.
.br
.BR udata
attr=<value>
.RS
.TP
.BI set " set"
.br
The sampler plugin name
.TP
.BI metric " metric"
.br
The metric name
.TP
.BI udata " udata"
.br
The desired user-data. This is a 64b unsigned integer.
.RE

.SS Set the user data of multiple metrics using regular expression.
The user data of the first matched metric is set to the base value.
The base value is incremented by the given 'incr' value and then
sets to the user data of the consecutive matched metric and so on.
.br
.BR udata_regex
attr=<value>
.RS
.TP
.BI set " set"
.br
The metric set name.
.TP
.BI regex " regex"
.br
A regular expression to match metric names to be set
.TP
.BI base " base"
.br
The base value of user data (uint64)
.TP
.BI [incr " incr"]
.br
Increment value (int). The default is 0. If incr is 0,
the user data of all matched metrics are set
to the base value. Optional.
.RE

.SS Change the security parameters of LDMS sets using regular expression.
The set security change affects only the new clients or the new connections.
The clients that already have access to the set will be able to continue to get
set updates, regardless of their permission.

To apply the new set security to the aggregators, on the first level
aggregator, users will stop and start the producer from which the set has been
aggregated. After the connection has been re-established, the first-level
aggregator can see the set if its permission matches the new set security.
There are no steps to perform on higher-level aggregators. Given that the
first-level aggregator has permission to see the set, it will compare the
second-level aggregator’s permission with the set security after successfully
looking up the set. The second-level aggregator will be able to look up the set
if it has permission to do so. The process continues on the higher-level
aggregators automatically.
.br
.BR set_sec_mod
attr=<value>
.RS
.TP
.BI regex " regex
.br
A regular expression to match set instance names
.TP
.BI [uid " uid"]
.br
An existing user name string or a UID. Optional
.TP
.BI [gid " gid"]
.br
A GID. Optional
.TP
.BI [perm " perm"]
.br
An octal number representing the permission bits. Optional
.RE

.SH MISC COMMAND SYNTAX

.SS Display the list of available commands
.br
.BR help
<command>
.RS
.RI [ command]
.br
If a command is given, the help of the command will be printed. Otherwise, only
the available command names are printed.
.RE

.SS Get the LDMS version the running LDMSD is based on.
.BR version



.SH NOTES
.IP \[bu]
ldmsctl is currently kept for backwards compatibility purposes with LDMS v2 commands.
ldmsctl still works in version 3, however with ldmsctl, some capabilitites use v2 pathways as opposed to v3.
.IP \[bu]
ldmsctl will be removed in a future release. It is not recommended that you use this with v2.

.SH BUGS
No known bugs.

.SH EXAMPLES

.HP
1) Run ldmsctl

.nf
$/tmp/opt/ovis/sbin/ldmsctl -h vm1_2 -p 10001 -x sock
ldmsctl>
.fi

.HP
2) After starting ldmsctl, configure "meminfo" collector plugin to collect every
second.

.nf
Note: interval=<# usec> e.g interval=1000000 defines a one second interval.
ldmsctl> load name=meminfo
ldmsctl> config name=meminfo component_id=1 set=vm1_1/meminfo
ldmsctl> start name=meminfo interval=1000000
ldmsctl> quit
.fi

.HP
3) Configure collectors on host "vm1" via bash script called collect.sh

.nf
#!/bin/bash
# Configure "meminfo" collector plugin to collect every second (1000000 usec) on vm1_2
echo "load name=meminfo"
echo "config name=meminfo component_id=2 set=vm1_2/meminfo"
echo "start name=meminfo interval=1000000"
# Configure "vmstat" collector plugin to collect every second (1000000 usec) on vm1_2
echo "load name=vmstat"
echo "config name=vmstat component_id=2 set=vm1_2/vmstat"
echo "start name=vmstat interval=1000000"

Make collect.sh executable
chmod +x collect.sh

Execute collect.sh (Note: When executing this across many nodes you would use pdsh to execute the script on all nodes
in parallel)
> ldmsd -x sock:11111 -l ldmsd.log
> ldmsctl -x sock -p 11111 -h localhost -X collect.sh
.fi

.HP
4) Example of updtr_match_list's report
.nf
ldmsctl> updtr_add name=meminfo_vmstat interval=1000000 offset=100000
ldmsctl> updtr_match_add name=meminfo_vmstat regex=meminfo match=schema
ldmsctl> updtr_match_add name=meminfo_vmstat regex=vmstat match=schema
ldmsctl>
ldmsctl> updtr_add name=node01_procstat2 interval=2000000 offset=100000
ldmsctl> updtr_match_add name=node01_procstat2 regex=node01/procstat2 match=inst
ldmsctl> updtr_match_list
Updater Name      Regex              Selector
----------------- ------------------ --------------
meminfo_vmstat
                  vmstat             schema
                  meminfo            schema
node01_procstat2
                  node01/procstat2   inst
ldmsctl>
.fi

.HP
5) Example of log_status's report
.nf
ldmsctl> log_status
Name                 Levels                         Description
-------------------- ------------------------------ ------------------------------
ldmsd (default)      ERROR,CRITICAL                 The default log subsystem
config               default                        Messages for the configuration infrastructure
failover             default                        Messages for the failover infrastructure
producer             default                        Messages for the producer infrastructure
sampler              default                        Messages for the common sampler infrastructure
store                default                        Messages for the common storage infrastructure
stream               default                        Messages for the stream infrastructure
updater              default                        Messages for the updater infrastructure
xprt.ldms            default                        Messages for ldms
xprt.zap             default                        Messages for Zap
xprt.zap.sock        default                        Messages for zap_sock
----------------------------------------------------------------------------------
The loggers with the Log Level as 'default' use the same log level as the
default logger (ldmsd). When the default log level changes, their log levels
change accordingly.
.fi

.HP
6) Change the log level of the config infrastructure to INFO and above
.nf
ldmsctl> loglevel name=config level=INFO
ldmsctl> log_status
Name                 Log Level                      Description
-------------------- ------------------------------ ------------------------------
ldmsd (default)      ERROR,CRITICAL                 The default log subsystem
config               INFO,WARNING,ERROR,CRITICAL    Messages for the configuration infrastructure
failover             default                        Messages for the failover infrastructure
producer             default                        Messages for the producer infrastructure
sampler              default                        Messages for the common sampler infrastructure
store                default                        Messages for the common storage infrastructure
stream               default                        Messages for the stream infrastructure
updater              default                        Messages for the updater infrastructure
xprt.ldms            default                        Messages for ldms
xprt.zap             default                        Messages for Zap
xprt.zap.sock        default                        Messages for zap_sock
----------------------------------------------------------------------------------
The loggers with the Log Level as 'default' use the same log level as the
default logger (ldmsd). When the default log level changes, their log levels
change accordingly.
.fi

.HP
7) Change the transport-related log levels to ERROR. That is, only the ERROR messages will be reported.
.nf
ldmsctl> loglevel regex=xprt.* level=ERROR,
ldmsctl> log_status
Name                 Log Level                      Description
-------------------- ------------------------------ ------------------------------
ldmsd (default)      ERROR,CRITICAL                 The default log subsystem
config               INFO,WARNING,ERROR,CRITICAL    Messages for the configuration infrastructure
failover             default                        Messages for the failover infrastructure
producer             default                        Messages for the producer infrastructure
sampler              default                        Messages for the common sampler infrastructure
store                default                        Messages for the common storage infrastructure
stream               default                        Messages for the stream infrastructure
updater              default                        Messages for the updater infrastructure
xprt.ldms            ERROR,                         Messages for ldms
xprt.zap             ERROR,                         Messages for Zap
xprt.zap.sock        ERROR,                         Messages for zap_sock
----------------------------------------------------------------------------------
The loggers with the Log Level as 'default' use the same log level as the
default logger (ldmsd). When the default log level changes, their log levels
change accordingly.
.fi

.HP
8) Set the log levels of all infrastructures to the default level
.nf
ldmsctl> loglevel regex=.* level=default
ldmsctl> log_status
Name                 Log Level                      Description
-------------------- ------------------------------ ------------------------------
ldmsd (default)      ERROR,CRITICAL                 The default log subsystem
config               default                        Messages for the configuration infrastructure
failover             default                        Messages for the failover infrastructure
producer             default                        Messages for the producer infrastructure
sampler              default                        Messages for the common sampler infrastructure
store                default                        Messages for the common storage infrastructure
stream               default                        Messages for the stream infrastructure
updater              default                        Messages for the updater infrastructure
xprt.ldms            default                        Messages for ldms
xprt.zap             default                        Messages for Zap
xprt.zap.sock        default                        Messages for zap_sock
----------------------------------------------------------------------------------
The loggers with the Log Level as 'default' use the same log level as the
default logger (ldmsd). When the default log level changes, their log levels
change accordingly.
.fi

.HP
9) Get the information of a specific log infrastructure
.nf
ldmsctl> log_status name=config
Name                 Log Level                      Description
-------------------- ------------------------------ ------------------------------
ldmsd (default)      ERROR,CRITICAL                 The default log subsystem
config               default                        Messages for the configuration infrastructure
----------------------------------------------------------------------------------
The loggers with the Log Level as 'default' use the same log level as the
default logger (ldmsd). When the default log level changes, their log levels
change accordingly.
ldmsctl>
.fi

.\
.\.PP
.nf
.\4) Example lines for adding hosts to an aggregator:
.\ldmsctl> add host=vm1_1 type=active interval=1000000 xprt=sock port=60020 sets=vm1_1/meminfo
.\ldmsctl> add host=vm1_1 type=active interval=1000000 xprt=sock port=60020 sets=vm1_1/vmstat
.\ldmsctl> add host=vm1_2 type=active interval=1000000 xprt=sock port=60020 sets=vm1_2/meminfo
.\ldmsctl> add host=vm1_2 type=active interval=1000000 xprt=sock port=60020 sets=vm1_2/vmstat
.\.fi
.\
.\.PP
.\.nf
.\5) Example lines for configuring one store type but for 2 different metric sets:
.\ldmsctl> load name=store_csv
.\ldmsctl> config name=store_csv path=/XXX/stored_data
.\ldmsctl> store name=store_csv comp_type=node set=meminfo container=meminfo
.\ldmsctl> store name=store_csv comp_type=node set=vmstat container=vmstat
.\.fi
.\
.\.PP
.\.nf
.\6) Chaining aggregators and storing:
.\ldmsctl> add host chama-rps1 type=active interval=1000000 xprt=sock port=60020 sets=foo/meminfo, foo/vmstat,foo/procnetdev
.\ldmsctl> add host chama-rps1 type=active interval=1000000 xprt=sock port=60020 sets=bar/meminfo, bar/vmstat,bar/procnetdev
.\ldmsctl> load name=store_csv
.\ldmsctl> config name=store_csv path=/projects/ovis/ClusterData/chama/storecsv
.\ldmsctl> store name=store_store_csv comp_type=node set=vmstat container=vmstat
.\ldmsctl> store name=store_store_csv comp_type=node set=meminfo container=meminfo
.\
.\Notes for example 6:
.\* You can do the add host more than once, but only for different prefix on the sets (foo vs bar).
.\* Syntax for add host is sets plural with comma separation.
.\* Syntax for store is only 1 set at a time.
.\* CSV file will be <path>/<comp_type>/<container>.
.\* Do not mix containers across sets
.\* Cannot put all the foo and bar in the same line.
.\.RE
.\.fi


.SH SEE ALSO
ldms_authentication(7), ldmsd(8), ldms_ls(8), ldmsd_controller(8), ldms_quickstart(7)
