.TH LSDATE "1" "June 2018" "LDMS utils" "User Commands"
.SH NAME
lsdate \- list directory contents with UTC timestamp suffix translation
.SH SYNOPSIS
.B lsdate
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
Execute ls(1) and apply an output filter to reveal the calendar date
of timestamp suffixed files, such as produced by LDMS CVS stores. 
Timestamps are assumed to be seconds since the epoch. Fractional seconds
are not supported.

.SH "SEE ALSO"
ls(1), Plugin_store_csv(7)

.SH NOTES
The output of lsdate -s and the output of lsdate -l may be surprising.
