.\" Manpage for Plugin_all_example
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "27 Feb 2017" "v3" "LDMS Plugin all_example man page"

.SH NAME
Plugin_all_example - man page for the LDMS all_example plugin

.SH SYNOPSIS
Within ldmsd_controller or a configuration file:
.br
config name=all_example [ <attr>=<value> ]

.SH DESCRIPTION
With LDMS (Lightweight Distributed Metric Service), plugins for the ldmsd (ldms daemon) are configured via ldmsd_controller
or a configuration file. The all_example plugin provides coding example for all metric types and a known data set for transmission and storage tests. The expected values are 76 or 'L', as appropriate to the data type.

.SH CONFIGURATION ATTRIBUTE SYNTAX

.TP
.BR config
name=<plugin_name> producer=<pname> instance=<set_name> [schema=<sname>] [component_id=<compid>]
.br
configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be all_example.
.TP
producer=<pname>
.br
The producer string value.
.TP
instance=<set_name>
.br
The name of the metric set.
.TP
schema=<schema>
.br
Optional schema name. It is intended that the same sampler on different nodes with different metrics have a
different schema. If not specified, will default to `all_example`.
.TP
component_id=<compid>
.br
Optional component identifier. Defaults to zero.
.RE

.SH BUGS
No known bugs.

.SH EXAMPLES
.PP
Within ldmsd_controller or a configuration file:
.nf
load name=all_example
config name=all_example producer=vm1_1 instance=vm1_1/all_example
start name=all_example interval=1000000
.fi

.SH SEE ALSO
ldmsd(8), ldms_quickstart(7), ldmsd_controller(8)
