.\" Manpage for Plugin_kgnilnd
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "10 Feb 2018" "v4" "LDMS Plugin kgnilnd man page"

.SH NAME
Plugin_kgnilnd - man page for the LDMS kgnilnd plugin

.SH SYNOPSIS
Within ldmsd_controller or in a configuration file
.br
config name=kgnilnd [ <attr>=<value> ]

.SH DESCRIPTION
With LDMS (Lightweight Distributed Metric Service), plugins for the ldmsd (ldms daemon) are configured via ldmsd_controller
or a configuration file. The kgnilnd plugin provides Cray specific info from /proc/kgnilnd.

.SH CONFIGURATION ATTRIBUTE SYNTAX
The kgnilnd plugin uses the sampler_base base class. This man page covers only the configuration attributes, or those with default values, specific to the this plugin; see ldms_sampler_base.man for the attributes of the base class.

.TP
.BR config
name=<plugin_name> [schema=<sname>]
.br
configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be kgnilnd.
.TP
schema=<schema>
.br
Optional schema name. It is intended that the same sampler on different nodes with different metrics have a
different schema. If not specified, will default to `kgnilnd`.
.RE

.SH BUGS
No known bugs.

.SH EXAMPLES
Within ldmsd_controller or in a configuration file
.nf
load name=kgnilnd
config name=kgnilnd producer=vm1_1 instance=vm1_1/kgnilnd
start name=kgnilnd interval=1000000
.fi

.SH SEE ALSO
ldmsd(8), Plugin_cray_system_sampler_variants(7), ldms_quickstart(7), ldmsd_controller(8), ldms_sampler_base(7)
