.\" Manpage for Plugin_procnfs
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "10 Feb 2018" "v4" "LDMS Plugin procnfs man page"

.SH NAME
Plugin_procnfs - man page for the LDMS procnfs plugin

.SH SYNOPSIS
Within ldmsd_controller or a configuration file:
.br
config name=procnfs [ <attr>=<value> ]

.SH DESCRIPTION
With LDMS (Lightweight Distributed Metric Service), plugins for the ldmsd (ldms daemon) are configured via ldmsd_controller
or a configuration file.
The procnfs plugin provides info from /proc/net/rpc/nfs

.SH CONFIGURATION ATTRIBUTE SYNTAX
The procnfs plugin uses the sampler_base base class. This man page covers only the configuration attributes, or those with default values, specific to the this plugin; see ldms_sampler_base.man for the attributes of the base class.

.TP
.BR config
name=<plugin_name> [schema=<sname>]
.br
configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be procnfs.
.TP
schema=<schema>
.br
Optional schema name. It is intended that the same sampler on different nodes with different metrics have a
different schema. If not specified, will default to `procnfs`.
.RE

.SH BUGS
No known bugs.

.SH EXAMPLES
.PP
.nf
Within ldmsd_controller or a configuration file:
load name=procnfs
config name=procnfs producer=vm1_1 instance=vm1_1/procnfs
start name=procnfs interval=1000000
.fi

.SH SEE ALSO
ldmsd(8), ldms_quickstart(7), ldmsd_controller(8), ldms_sampler_base(7)
