.\" Manpage for Plugin_clock
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "18 Feb 2018" "v4" "LDMS Plugin clock man page"

.SH NAME
Plugin_clock - man page for the LDMS clock plugin

.SH SYNOPSIS
Within ldmsd_controller or a configuration file:
.br
config name=clock [ <attr>=<value> ]

.SH DESCRIPTION
The clock plugin provides a counter of samples taken since it started.
This is of pedagogical interest and useful for detecting situations where
a sample is missed either in being taken or in transmission.

.SH CONFIGURATION ATTRIBUTE SYNTAX
The clock plugin uses the sampler_base base class. This man page covers only the configuration attributes, or those with\
 default values, specific to the this plugin; see ldms_sampler_base.man for the attributes of the base class.


.TP
.BR config
name=<plugin_name> [schema=<sname>]
.br
configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be clock
.TP
schema=<schema>
.br
Optional schema name. It is intended that the same sampler on different nodes with different metrics have a
different schema. If not specified, will default to `clock`.
.RE

.SH BUGS
No known bugs.

.SH EXAMPLES
.PP
Within ldmsd_controller or a configuration file:
.nf
load name=clock
config name=clock producer=vm1_1 instance=vm1_1/clock
start name=clock interval=1000000 offset=0
.fi

.SH SEE ALSO
ldmsd(8), ldms_quickstart(7), ldmsd_controller(8), ldms_sampler_base(7)
