.\" Manpage for Plugin_lnet_stats
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "18 Feb 2018" "v4" "LDMS Plugin lnet stats man page"

.SH NAME
Plugin_lnet_stats - man page for the LDMS lnet_stats plugin

.SH SYNOPSIS
Within ldmsctl
.br
ldmsctl> config name=lnet_stats [ <attr>=<value> ]

.SH DESCRIPTION
With LDMS (Lightweight Distributed Metric Service), plugins for the ldmsd (ldms daemon) are configured via ldmsd_controller or a configuration file.
The lnet_stats plugin provides memory info from /proc/sys/lnet/stats or
equivalent.

.SH CONFIGURATION ATTRIBUTE SYNTAX
The lnet_stats plugin uses the sampler_base base class. This man page covers only the configuration attributes, or those with default values, specific to the this plugin; see ldms_sampler_base.man for the attributes of the base class.

.TP
.BR config
name=<plugin_name> [schema=<sname> file=<stats_path>]
.br
ldmsctl configuration line.
.RS
.TP
name=<plugin_name>
.br
This MUST be lnet_stats.
.TP
schema=<schema>
.br
Optional schema name. It is intended that the same sampler on different nodes with different metrics have a
different schema. If not specified, will default to `lnet_stats`.
.TP
file=<stats_path>
.br
Optional full path name of stats file if not in default location.

.SH NOTES
.PP
The default location for the lnet stats path is:
/sys/kernel/debug/lnet/stats, and /proc/sys/lnet/stats depends on the Lustre version. Be aware that /sys/kernel/debug is only readable by privileged users.

.RE



.SH BUGS
Assumes file name instead of looking it up from the Lustre runtime libraries,
to avoid compile time dependence on Lustre. This will not be fixed.
Does not define meta metrics as it should.

.SH EXAMPLES
.PP
.nf
Within ldmsd_controller or a configuration file:
load name=lnet_stats
config name=lnet_stats producer=vm1_1 instance=vm1_1/lnet_stats component_id=10
start name=lnet_stats interval=1000000

.fi

.SH SEE ALSO
ldmsd(8), ldms_quickstart(7), ldmsd_controller(8), ldms_sampler_base(7)
