.\" Manpage for ldmsctl_args3 
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 8 "29 Aug 2017" "v3.4" "ldmsd man page"

.SH NAME
ldmsctl_args3  \- Compute ldmsd configuration commands from genders data for a host.

.SH SYNOPSIS
ldmsctl_args3 [OPTION...]

.SH DESCRIPTION
The ldmsctl_args3 generates configuration commands needed for an 
an ldms daemon based on a genders input file.

.SH OPTIONS
.SS
General/Configuration Options:
.TP
.BI -g/--genders " file"
Process the genders file named. Default is /etc/genders
.TP
.BI -n/--node " hostname"
Emit results for the given host.
.TP
.BI -t/--task " TASK"
Emit results for the given TASK, which is currently host-list (aggregator configuration)
and store-list (a list of schema detected and visible at the given node.
.TP
.BI -i/--interval " INTERVAL"
.br
INTERVAL value overriding interval_default gender.
.TP
.BI -o " OFFSET"
OFFSET value overriding offset_default gender.
.TP
.BI -v/--verbose " N"
Emit debugging messages for N > 0. Higher N gives more info.
.TP
.BR -O/--output " file"
Dump result to file instead of screen.

.SH NOTES
Task options are in development.

.SH BUGS
Output option does not work yet.

.SH EXAMPLES
.PP
.nf
$ ldmsctl_args3 -g genders.in.test -n cluster_admin1
.br
.fi


.SH SEE ALSO
ldms-attributes(5), ldmsd-genders(8)

