#!/bin/bash

#The following is the interface to the script ldms_control that this script will call
#------------------------------------------------------
# LDMS_ENTITY is one of ldmsd, meminfo, vmstat, geminfo, procinterrupts, procpidstatic, procstat, ldmsmon
# ACTION is one of start, stop, resume, remove
# SOCKET is the name of the socket to be created by ldmsd and used for communication with ldmsd
# PERIOD is the number of micro-seconds between collection
# COMP_ID is the component identifier that will be asociated with this metric set (should be the same for same host)
# LDMS_LIB_PATH is the path to the ldms libraries as seen from the host being collected on
# LDMS_EXE_PATH is the path to the ldms executables as seen from the host being collected on
# LDMS_LOG_PATH is the path to the ldms logfile entries as seen from the host being collected on

#LDMS_ENTITY=$1
#ACTION=$2
#SOCKET=$3
#PERIOD=$4
#COMP_ID=$5
#LDMS_LIB_PATH=$6
#LDMS_EXE_PATH=$7
#LDMS_LOG_PATH=$8
#LDMS_TRANSPORT=$9
#--------------------------------------------------

# MYHOSTS is the hostfile specifying the hosts to run ldmsd on
# MYCONFIGS is the file specifying the 
HOST=$1
COMP_ID=$2
SOCKET=$3
MYCONFIGS=$4

CTRLHOST_PATH_TO_BASE="$(cat ldms_base_config | grep "CTRLHOST" | cut -d , -f4 | sed 's/^[ \t]*//')"
SHARED_PATH_TO_SCRIPTS="$(cat ldms_base_config | grep "SHARED" | cut -d , -f4 | sed 's/^[ \t]*//')"
SHARED_PATH_TO_LDMS_LIBS="$(cat ldms_base_config | grep "SHARED" | cut -d , -f5 | sed 's/^[ \t]*//')"
SHARED_PATH_TO_LDMS_EXE="$(cat ldms_base_config | grep "SHARED" | cut -d , -f6 | sed 's/^[ \t]*//')"
SHARED_PATH_TO_LDMS_LOGS="$(cat ldms_base_config | grep "SHARED" | cut -d , -f7 | sed 's/^[ \t]*//')"
EXEPREFIX="$(cat ldms_base_config | grep "EXEPREFIX" | cut -d , -f2 | sed 's/^[ \t]*//')"


exec 9<$MYCONFIGS
while read -u9 line
   do
	LDMS_ENTITY=$(echo $line | cut -d ' ' -f1 | sed 's/^[ \t]*//')
	ACTION=$(echo $line | cut -d ' ' -f2 | sed 's/^[ \t]*//')
	PERIOD=$(echo $line | cut -d ' ' -f3 | sed 's/^[ \t]*//')
	if [[ -z $LDMS_ENTITY && -z $ACTION && -z $PERIOD ]]; then
		continue
	elif [[ -z $LDMS_ENTITY || -z $ACTION || -z $PERIOD ]]; then
		echo "Bad file syntax in file $MYCONFIGS: ldms_entity  action  collection_period"
		break
        elif [[ $LDMS_ENTITY = "#" ]]; then
                continue
	fi
	echo "ssh $HOST \"$EXEPREFIX $SHARED_PATH_TO_SCRIPTS/ldms_control $LDMS_ENTITY $ACTION $SOCKET $PERIOD $COMP_ID $SHARED_PATH_TO_LDMS_LIBS $SHARED_PATH_TO_LDMS_EXE $SHARED_PATH_TO_LDMS_LOGS $LDMS_TRANSPORT > /dev/null 2>&1 &\""
	ssh $HOST "$EXEPREFIX $SHARED_PATH_TO_SCRIPTS/ldms_control $LDMS_ENTITY $ACTION $SOCKET $PERIOD $COMP_ID $SHARED_PATH_TO_LDMS_LIBS $SHARED_PATH_TO_LDMS_EXE $SHARED_PATH_TO_LDMS_LOGS $LDMS_TRANSPORT > /dev/null 2>&1 &"
# Put in sleep because sometimes didn't work. Perhaps conflict when 2 scripts executing simultaneously
	sleep 0.1
   done
