#!/bin/bash

#The following is the interface to the script ldms_control that this script will call
#------------------------------------------------------
# LDMS_ENTITY is one of ldmsd, meminfo, vmstat, geminfo, procinterrupts, procpidstatic, procstat, ldmsmon
# ACTION is one of start, stop, resume, remove
# SOCKET is the name of the socket to be created by ldmsd and used for communication with ldmsd
# PERIOD is the number of micro-seconds between collection
# COMP_ID is the component identifier that will be asociated with this metric set (should be the same for same host)
# LDMS_LIB_PATH is the path to the ldms libraries as seen from the host being collected on
# LDMS_EXE_PATH is the path to the ldms executables as seen from the host being collected on
# LDMS_LOG_PATH is the path to the ldms logfile entries as seen from the host being collected on

#LDMS_ENTITY=$1
#ACTION=$2
#SOCKET=$3
#PERIOD=$4
#COMP_ID=$5
#LDMS_LIB_PATH=$6
#LDMS_EXE_PATH=$7
#LDMS_LOG_PATH=$8
#LDMS_TRANSPORT=$9
#--------------------------------------------------

# MYHOSTS is the hostfile specifying the hosts to run ldmsd on
# MYCONFIGS is the file specifying the 
HOST=$1
COMP_ID=$2
SOCKET=$3
LDMSD_PERIOD=$4
LDMS_TRANSPORT=$5

CTRLHOST_PATH_TO_BASE="$(cat ldms_base_config | grep "CTRLHOST" | cut -d , -f4 | sed 's/^[ \t]*//')"
SHARED_PATH_TO_SCRIPTS="$(cat ldms_base_config | grep "SHARED" | cut -d , -f4 | sed 's/^[ \t]*//')"
SHARED_PATH_TO_LDMS_LIBS="$(cat ldms_base_config | grep "SHARED" | cut -d , -f5 | sed 's/^[ \t]*//')"
SHARED_PATH_TO_LDMS_EXE="$(cat ldms_base_config | grep "SHARED" | cut -d , -f6 | sed 's/^[ \t]*//')"
SHARED_PATH_TO_LDMS_LOGS="$(cat ldms_base_config | grep "SHARED" | cut -d , -f7 | sed 's/^[ \t]*//')"
EXEPREFIX="$(cat ldms_base_config | grep "EXEPREFIX" | cut -d , -f2 | sed 's/^[ \t]*//')"
#SHARED_PATH_TO_PAPI="$(cat ldms_base_config | grep "SHARED" | cut -d , -f9 | sed 's/^[ \t]*//')"

	echo "ssh $HOST \"$EXEPREFIX $SHARED_PATH_TO_SCRIPTS/ldms_control ldmsd start $SOCKET $LDMSD_PERIOD $COMP_ID $SHARED_PATH_TO_LDMS_LIBS $SHARED_PATH_TO_LDMS_EXE $SHARED_PATH_TO_LDMS_LOGS $LDMS_TRANSPORT > /dev/null 2>&1 &\""
	ssh $HOST "$EXEPREFIX $SHARED_PATH_TO_SCRIPTS/ldms_control ldmsd start $SOCKET $LDMSD_PERIOD $COMP_ID $SHARED_PATH_TO_LDMS_LIBS $SHARED_PATH_TO_LDMS_EXE $SHARED_PATH_TO_LDMS_LOGS $LDMS_TRANSPORT > /dev/null 2>&1 &"
