#!/bin/bash

#The following is the interface to the script ldms_control that this script will call
#------------------------------------------------------
# LDMS_ENTITY is one of ldmsd, meminfo, vmstat, geminfo, procinterrupts, procpidstatic, procstat, ldmsmon
# ACTION is one of start, stop, resume, remove
# SOCKET is the name of the socket to be created by ldmsd and used for communication with ldmsd
# PERIOD is the number of micro-seconds between collection
# COMP_ID is the component identifier that will be asociated with this metric set (should be the same for same host)
# LDMS_LIB_PATH is the path to the ldms libraries as seen from the host being collected on
# LDMS_EXE_PATH is the path to the ldms executables as seen from the host being collected on
# LDMS_LOG_PATH is the path to the ldms logfile entries as seen from the host being collected on

#LDMS_ENTITY=$1
#ACTION=$2
#SOCKET=$3
#PERIOD=$4
#COMP_ID=$5
#LDMS_LIB_PATH=$6
#LDMS_EXE_PATH=$7
#LDMS_LOG_PATH=$8
#LDMS_TRANSPORT=$9
#--------------------------------------------------

# MYHOSTS is the hostfile specifying the hosts to run ldmsd on
# MYCONFIGS is the file specifying the ldms entities and how to apply them on MYHOSTS
# STREAM_NUM is the particular external data stream defined in ldms_base_config and is numbered starting at 1
# LDMS_TRANSPORT is one of "sock" or "rdma"

MYHOSTS=$1
DAEMON_NUM=$2
STREAM_NUM=$3
LDMS_TRANSPORT=$4
CNTRL=$5

count=0

if [[ -z $MYHOSTS  || -z $STREAM_NUM || -z $LDMS_TRANSPORT || -z $DAEMON_NUM ]]; then 
	echo "Bad syntax: launch_base <host file> <daemon number> <stream number> <transport type> [BEGIN]"
	exit
fi

BASEPORT="$(cat ldms_base_config | grep "BASEPORT" | cut -d , -f2 | sed 's/^[ \t]*//')"
CTRLHOST_PATH_TO_LDMS_BASE="$(cat ldms_base_config | grep "CTRLHOST" | cut -d , -f4 | sed 's/^[ \t]*//')"
#SOCKET=$(( $BASEPORT + $STREAM_NUM - 1 ))
HOST_SOCKET=$(( $BASEPORT + $DAEMON_NUM - 1 ))
STREAM_SOCKET=$(( $BASEPORT + $STREAM_NUM - 1 ))
if [[ $CNTRL = "BEGIN" ]]; then
   $CTRLHOST_PATH_TO_LDMS_BASE/build_utils
fi

exec 9<$MYHOSTS
while read -u9 line
   do
	host=$(echo $line | cut -d ' ' -f1 | sed 's/^[ \t]*//')
	host_comp_id_base=$(echo $line | cut -d ' ' -f2 | sed 's/^[ \t]*//')
	period=$(echo $line | cut -d ' ' -f3 | sed 's/^[ \t]*//')
	if [[ -z $host && -z $comp_id && -z $period ]]; then
		continue
	elif [[ -z $host || -z $host_comp_id_base || -z $period ]]; then
		echo "Bad file format in file $MYHOSTS: host  component_id  collection_period"
		break
	elif [[ $host = "#" ]]; then
		continue
	fi
#	echo "In start_ldmsd: Socket = $HOST_SOCKET, period = $period"
	$CTRLHOST_PATH_TO_LDMS_BASE/build_config $STREAM_NUM $STREAM_SOCKET $host $HOST_SOCKET $period
#	echo "$CTRLHOST_PATH_TO_LDMS_BASE/build_config $STREAM_NUM $STREAM_SOCKET $host $HOST_SOCKET $period"
#	$CTRLHOST_PATH_TO_LDMS_BASE/run_ldmsd $host $comp_id $HOST_SOCKET $period $LDMS_TRANSPORT 
        comp_id=$(( $host_comp_id_base + $DAEMON_NUM - 1 ))
	$CTRLHOST_PATH_TO_LDMS_BASE/run_ldmsd $host $comp_id $HOST_SOCKET $period $LDMS_TRANSPORT
#	echo "Stream = $STREAM_NUM, $CTRLHOST_PATH_TO_LDMS_BASE/run_ldmsd $host $comp_id $HOST_SOCKET $period $LDMS_TRANSPORT"
   done
   if [[ $CNTRL != "FINISHED" ]]; then
	$CTRLHOST_PATH_TO_LDMS_BASE/build_config $STREAM_NUM $STREAM_SOCKET finish $HOST_SOCKET 1000000
   fi
