.\" Manpage for Plugin_edac
.\" Contact ovis-help@sandia.gov to correct errors or typos.
.TH man 7 "19 Jan 2017" "v3" "LDMS Plugin edac man page"

.SH NAME
Plugin_edac - man page for the LDMS edac plugin

.SH SYNOPSIS
Within ldmsd_controller
.br
config name=edac [ <attr> = <value> ]

.SH DESCRIPTION
The edac plugin provides memory error information from /sys/devices/system/edac
for correctable and uncorrectable errors.

.SH CONFIGURATION ATTRIBUTE SYNTAX

.TP
.BR config
name=<plugin_name> component_id=<comp_id> max_mc=<max_mc> max_csrow=<max_csrow> set=<set_name> 
.br
 configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be edac.
.TP
producer=<pname>
.br
The producer string value.
.TP
instance=<set_name>
.br
The name of the metric set.
.TP
schema=<schema>
.br
Optional schema name. It is intended that the same sampler on different nodes with different metrics have a
different schema. If not specified, will default to edac.
.TP
component_id=<comp_id>
.br
The component id numerical value.
with_jobid=<bool>
.br
Option to collect job id with set or 0 if not.
.TP
max_mc=<max_mc>
.br
The number of mc's in /sys/devices/system/edac/mc. Typically this number is 2.
.TP
max_csrow=<max_csrow>
.br
The number of csrows in a single mc. For example, the value should be 4 for when the largest csrow looks like: /sys/devices/system/edac/mc/mc0/csrow3. Typically this number is 8, but it can vary depending on the system.
.RE

.SH DATA
This reports counts for both correctable and uncorrectable errors per mc and per csrow. It also reports the seconds since reset per mc.

.SH EXAMPLES 
.PP
Within ldmsd_controller or a configuration file:
.nf
load name=edac
config name=edac producer=vm1_1 component_id=1 instance=vm1_1/edac max_mc=2 max_csrow=4 
start name=edac interval=1000000
.fi

.SH NOTES
.PP
An upper limit on metric set size is enforced. Configuring to collect too many registers will generate an error detailing the compiled size limit. This limit is only adjustable in the source code.
.PP
For more detailed background information,
see www.kernel.org/doc/Documentation/edac.txt and www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-edac.

.SH AUTHORS
Kathleen Shoga <shoga1@llnl.gov> (Lawrence Livermore National Laboratory).
Ported to LDMS v3 by Benjamin Allan <baallan@sandia.gov>.

.SH ACKNOWLEDGMENTS
This work was created under the auspices of the U.S. Department of Energy by Lawrence Livermore National Laboratory under Contract DE-AC52-07NA27344. Release Number: LLNL-SM-687054.

.SH SEE ALSO
edac(3), edac-util(8), edac-ctl(8), ldms(7)
