#!/bin/bash

cd base
/projects/ldms/ldms_utils/base/control_plugins \
/projects/ldms/ldms_utils/configs/my_hosts \
/projects/ldms/ldms_utils/configs/my_stop_perf_events \
2 \
sock

/projects/ldms/ldms_utils/base/control_plugins \
/projects/ldms/ldms_utils/configs/my_hosts \
/projects/ldms/ldms_utils/configs/my_remove_perf_events \
2 \
sock


