#!/bin/bash
# Args are hosts, plugins, stream num (must be one in ldms_base_config), transport (sock or rdma)

cd base
/projects/ldms/ldms_utils/base/control_plugins \
/projects/ldms/ldms_utils/configs/my_hosts \
/projects/ldms/ldms_utils/configs/my_start_plugins \
1 \
sock


