env SAMPLE_INTERVAL=1000000
env SAMPLE_OFFSET=0
env PROCTYPE=x86_ven0002fam0019mod0001

msg_enable
stream_enable

load name=meminfo
config name=meminfo producer=${HOSTNAME} instance=${HOSTNAME}/meminfo component_id=${COMPONENT_ID} schema=meminfo job_set=${HOSTNAME}/slurm
start name=meminfo interval=${SAMPLE_INTERVAL} offset=${SAMPLE_OFFSET}

load name=procstat
config name=procstat producer=${HOSTNAME} instance=${HOSTNAME}/procstat component_id=${COMPONENT_ID} schema=procstat_${PROCTYPE} job_set=${HOSTNAME}/slurm
start name=procstat interval=${SAMPLE_INTERVAL} offset=${SAMPLE_OFFSET}

load name=loadavg
config name=loadavg producer=${HOSTNAME} instance=${HOSTNAME}/loadavg component_id=${COMPONENT_ID} schema=loadavg job_set=${HOSTNAME}/slurm
start name=loadavg interval=${SAMPLE_INTERVAL} offset=${SAMPLE_OFFSET}

load name=hello_sampler
config name=hello_sampler producer=${HOSTNAME} instance=${HOSTNAME}/hello_sampler stream=nersc component_id=1
start name=hello_sampler interval=1000000 offset=0

