.\" Manpage for Plugin_sysclassib
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "10 Feb 2018" "v4" "LDMS Plugin sysclassib man page"

.SH NAME
Plugin_sysclassib - man page for the LDMS sysclassib plugin

.SH SYNOPSIS
Within ldmsd_controller or in a configuration file
.br
config name=sysclassib [ <attr> = <value> ]

.SH DESCRIPTION
The sysclassib plugin provides IB metric information in raw and rate (per second) forms.

.SH CONFIGURATION ATTRIBUTE SYNTAX
The sysclassib plugin uses the sampler_base base class. This man page covers only the configuration attributes, or those with default values, specific to the this plugin; see ldms_sampler_base.man for the attributes of the base class.

.TP
.BR config name=<plugin_name> [schema=<sname>]  ports=<ports> [metrics_type=<mtype>]
.br
configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be sysclassib.
.TP
metrics_type=<metrics_type>
.br
Values are 0 or 1. 0 = counter data only. 1 = include rate data (per second) in addition.
Default is 0.
.TP
ports=<ports>
.br
CSV list of the form CARD1.PORT1,CARD2.PORT2. Default is all discovered values.
.RE

.SH BUGS
No known bugs.

.SH EXAMPLES
.PP
Within ldmsd_controller or a configuration file:
.nf
load name=sysclassib
config name=sysclassib component_id=1 producer=vm1_1 instance=vm1_1/sysclassib metric_type=1
start name=sysclassib interval=1000000 offset=0
.fi

.SH SEE ALSO
ldms(7), Plugin_procnetdev(7), ldms_sampler_base(7)
