.\" Manpage for Plugin_dstat
.\" Contact ovis-help@sandia.gov to correct errors or typos.
.TH man 7 "20 May 2018" "v3.4.6" "LDMS Plugin dstat man page"

.SH NAME
Plugin_dstat - man page for the LDMS dstat plugin

.SH SYNOPSIS
Within ldmsd_controller
.br
config name=dstat [ <attr> = <value> ]

.SH DESCRIPTION
The dstat plugin provides ldmsd process information from /proc/self/[io,stat,statm].

.SH CONFIGURATION ATTRIBUTE SYNTAX

.TP
.BR config
name=<plugin_name> component_id=<comp_id> [io=<bool>] [stat=<bool>] [statm=<bool>] [mmalloc=<bool>] set=<set_name> 
.br
 configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be dstat.
.TP
producer=<pname>
.br
The producer string value.
.TP
instance=<set_name>
.br
The name of the metric set.
.TP
schema=<schema>
.br
Optional schema name. It is intended that the same sampler on different nodes with different metrics have a
different schema. If not specified, will default to dstat.
.TP
component_id=<comp_id>
.br
The component id numerical value.
with_jobid=<bool>
.br
Option to collect job id with set or 0 if not.
.TP
io=<bool>
.br
Include the metrics from /proc/self/io.
.TP
stat=<bool>
.br
Include the metrics from /proc/self/stat.
.TP
statm=<bool>
.br
Include the metrics from /proc/self/statm.
.TP
mmalloc=<bool>
.br
Include the mmap memory usage metric from LDMS mmalloc.
.RE

.SH DATA
This reports metrics from /proc/self/[io,stat,statm] by default. If specific subsets are named (io=true), then unnamed sets are suppressed. 
Units on the /proc metric values are documented in the man pages. The unit of the mmalloc metric is bytes.

.SH EXAMPLES 
.PP
Within ldmsd_controller or a configuration file:
.nf
load name=dstat
config name=dstat producer=vm1_1 component_id=1 instance=vm1_1/dstat
start name=dstat interval=1000000
.fi

.SH NOTES
.PP
See proc(5) for the definitions of the metrics. Metrics which are invariant (other than pids) are not included. Where naming is potentially ambiguous and a more specific name is used in /proc/self/status for the same metrics, the name from /proc/self/status is used.
.PP
Requesting mmalloc (which may be high overhead) requires explicitly requesting it and all others which are wanted. 
.PP
This is our answer to the ancient question "Quis custodiet ipsos custodes?"

.SH SEE ALSO
proc(5), ldmsd(8)
