#!/bin/bash
# Args are hosts, plugins, stream num (must be one in ldms_base_config), transport (sock or rdma)

NUM_STREAMS=$1

if [[ -z $NUM_STREAMS ]]; then
   echo "Warning -- Usage: start_my_plugins_mult <number of daemons per host>. Using number of daemons per host = 1"
   NUM_STREAMS=1
#   exit
fi
cd base
for ((i=1; i<=$NUM_STREAMS; i++)); do
   /home/brandt/ldms-async/ldms_utils/base/control_plugins \
   /home/brandt/ldms-async/ldms_utils/configs/my_hosts \
   /home/brandt/ldms-async/ldms_utils/configs/my_start_plugins \
   $i \
   sock
done


