#!/bin/bash
# Args are: hostfile, stream number (must match a stream in ldms_base_config, transport (sock or rdma)
DAEMONS_PER_NODE=$1
STREAMS_PER_NODE=$2

STATE=BEGIN
STREAM=1

if [[ -z $DAEMONS_PER_NODE ]]; then
      echo "Warning -- Usage: start_my_ldmsd_mult <number per host> <number streams per host>. Using number per host = 1"
      DAEMONS_PER_NODE=1
#   exit
fi
if [[ -z $STREAMS_PER_NODE ]]; then
      echo "Warning -- Usage: start_my_ldmsd_mult <number per host> <number streams per host>. Using number streams per host = 1"
      STREAMS_PER_NODE=1
#   exit
fi
   cd /home/brandt/ldms-async/ldms_utils/base/
#echo   "./start_ldmsd /home/brandt/ldms-async/ldms_utils/configs/my_hosts 1 $STREAM sock $STATE"
   ./start_ldmsd /home/brandt/ldms-async/ldms_utils/configs/my_hosts 1 $STREAM sock $STATE
   STATE=NORMAL
   for ((i=2; i<=$DAEMONS_PER_NODE; i++)); do
      STREAM=$(($(($i - 1)) % $STREAMS_PER_NODE + 1 ))
#      echo "stream = $STREAM, i = $i"
      if [[ $i -gt 1 && $STREAM -eq 1 ]]; then
         STATE=FINISHED
      fi
#echo      "./start_ldmsd /home/brandt/ldms-async/ldms_utils/configs/my_hosts $i $STREAM sock $STATE"
      ./start_ldmsd /home/brandt/ldms-async/ldms_utils/configs/my_hosts $i $STREAM sock $STATE
   done

