/* -*- c-basic-offset: 8 -*-
 * Copyright (c) 2018 National Technology & Engineering Solutions
 * of Sandia, LLC (NTESS). Under the terms of Contract DE-NA0003525 with
 * NTESS, the U.S. Government retains certain rights in this software.
 * Copyright (c) 2018 Open Grid Computing, Inc. All rights reserved.
 *
 * This software is available to you under a choice of one of two
 * licenses.  You may choose to be licensed under the terms of the GNU
 * General Public License (GPL) Version 2, available from the file
 * COPYING in the main directory of this source tree, or the BSD-type
 * license below:
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *      Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *      Redistributions in binary form must reproduce the above
 *      copyright notice, this list of conditions and the following
 *      disclaimer in the documentation and/or other materials provided
 *      with the distribution.
 *
 *      Neither the name of Sandia nor the names of any contributors may
 *      be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 *      Neither the name of Open Grid Computing nor the names of any
 *      contributors may be used to endorse or promote products derived
 *      from this software without specific prior written permission.
 *
 *      Modified source versions must be plainly marked as such, and
 *      must not be misrepresented as being the original software.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/**
 * \file mpi_profiler_func_list.h
 * \brief Routines to manage MPI functions and events
 */
#ifndef MPI_PROFILER_FUNC_LIST_H
#define MPI_PROFILER_FUNC_LIST_H

#define MAX_LDMS_SHM_MPI_FUNC_NAME 32

typedef enum {
	LDMS_SHM_MPI_Send_ID = 0,
	LDMS_SHM_MPI_Recv_ID,
	LDMS_SHM_MPI_Get_count_ID,
	LDMS_SHM_MPI_Bsend_ID,
	LDMS_SHM_MPI_Ssend_ID,
	LDMS_SHM_MPI_Rsend_ID,
	LDMS_SHM_MPI_Buffer_attach_ID,
	LDMS_SHM_MPI_Buffer_detach_ID,
	LDMS_SHM_MPI_Isend_ID,
	LDMS_SHM_MPI_Ibsend_ID,
	LDMS_SHM_MPI_Issend_ID,
	LDMS_SHM_MPI_Irsend_ID,
	LDMS_SHM_MPI_Irecv_ID,
	LDMS_SHM_MPI_Wait_ID,
	LDMS_SHM_MPI_Test_ID,
	LDMS_SHM_MPI_Request_free_ID,
	LDMS_SHM_MPI_Waitany_ID,
	LDMS_SHM_MPI_Testany_ID,
	LDMS_SHM_MPI_Waitall_ID,
	LDMS_SHM_MPI_Testall_ID,
	LDMS_SHM_MPI_Waitsome_ID,
	LDMS_SHM_MPI_Testsome_ID,
	LDMS_SHM_MPI_Iprobe_ID,
	LDMS_SHM_MPI_Probe_ID,
	LDMS_SHM_MPI_Cancel_ID,
	LDMS_SHM_MPI_Test_cancelled_ID,
	LDMS_SHM_MPI_Send_init_ID,
	LDMS_SHM_MPI_Bsend_init_ID,
	LDMS_SHM_MPI_Ssend_init_ID,
	LDMS_SHM_MPI_Rsend_init_ID,
	LDMS_SHM_MPI_Recv_init_ID,
	LDMS_SHM_MPI_Start_ID,
	LDMS_SHM_MPI_Startall_ID,
	LDMS_SHM_MPI_Sendrecv_ID,
	LDMS_SHM_MPI_Sendrecv_replace_ID,
	LDMS_SHM_MPI_Type_contiguous_ID,
	LDMS_SHM_MPI_Type_vector_ID,
	LDMS_SHM_MPI_Type_hvector_ID,
	LDMS_SHM_MPI_Type_indexed_ID,
	LDMS_SHM_MPI_Type_hindexed_ID,
	LDMS_SHM_MPI_Type_struct_ID,
	LDMS_SHM_MPI_Address_ID,
	LDMS_SHM_MPI_Type_extent_ID,
	LDMS_SHM_MPI_Type_size_ID,
	LDMS_SHM_MPI_Type_lb_ID,
	LDMS_SHM_MPI_Type_ub_ID,
	LDMS_SHM_MPI_Type_commit_ID,
	LDMS_SHM_MPI_Type_free_ID,
	LDMS_SHM_MPI_Get_elements_ID,
	LDMS_SHM_MPI_Pack_ID,
	LDMS_SHM_MPI_Unpack_ID,
	LDMS_SHM_MPI_Pack_size_ID,
	LDMS_SHM_MPI_Barrier_ID,
	LDMS_SHM_MPI_Bcast_ID,
	LDMS_SHM_MPI_Gather_ID,
	LDMS_SHM_MPI_Gatherv_ID,
	LDMS_SHM_MPI_Scatter_ID,
	LDMS_SHM_MPI_Scatterv_ID,
	LDMS_SHM_MPI_Allgather_ID,
	LDMS_SHM_MPI_Allgatherv_ID,
	LDMS_SHM_MPI_Alltoall_ID,
	LDMS_SHM_MPI_Alltoallv_ID,
	LDMS_SHM_MPI_Alltoallw_ID,
	LDMS_SHM_MPI_Exscan_ID,
	LDMS_SHM_MPI_Reduce_ID,
	LDMS_SHM_MPI_Op_create_ID,
	LDMS_SHM_MPI_Op_free_ID,
	LDMS_SHM_MPI_Allreduce_ID,
	LDMS_SHM_MPI_Reduce_scatter_ID,
	LDMS_SHM_MPI_Scan_ID,
	LDMS_SHM_MPI_Group_size_ID,
	LDMS_SHM_MPI_Group_rank_ID,
	LDMS_SHM_MPI_Group_translate_ranks_ID,
	LDMS_SHM_MPI_Group_compare_ID,
	LDMS_SHM_MPI_Comm_group_ID,
	LDMS_SHM_MPI_Group_union_ID,
	LDMS_SHM_MPI_Group_intersection_ID,
	LDMS_SHM_MPI_Group_difference_ID,
	LDMS_SHM_MPI_Group_incl_ID,
	LDMS_SHM_MPI_Group_excl_ID,
	LDMS_SHM_MPI_Group_range_incl_ID,
	LDMS_SHM_MPI_Group_range_excl_ID,
	LDMS_SHM_MPI_Group_free_ID,
	LDMS_SHM_MPI_Comm_size_ID,
	LDMS_SHM_MPI_Comm_rank_ID,
	LDMS_SHM_MPI_Comm_compare_ID,
	LDMS_SHM_MPI_Comm_dup_ID,
	LDMS_SHM_MPI_Comm_dup_with_info_ID,
	LDMS_SHM_MPI_Comm_create_ID,
	LDMS_SHM_MPI_Comm_split_ID,
	LDMS_SHM_MPI_Comm_free_ID,
	LDMS_SHM_MPI_Comm_test_inter_ID,
	LDMS_SHM_MPI_Comm_remote_size_ID,
	LDMS_SHM_MPI_Comm_remote_group_ID,
	LDMS_SHM_MPI_Intercomm_create_ID,
	LDMS_SHM_MPI_Intercomm_merge_ID,
	LDMS_SHM_MPI_Keyval_create_ID,
	LDMS_SHM_MPI_Keyval_free_ID,
	LDMS_SHM_MPI_Attr_put_ID,
	LDMS_SHM_MPI_Attr_get_ID,
	LDMS_SHM_MPI_Attr_delete_ID,
	LDMS_SHM_MPI_Topo_test_ID,
	LDMS_SHM_MPI_Cart_create_ID,
	LDMS_SHM_MPI_Dims_create_ID,
	LDMS_SHM_MPI_Graph_create_ID,
	LDMS_SHM_MPI_Graphdims_get_ID,
	LDMS_SHM_MPI_Graph_get_ID,
	LDMS_SHM_MPI_Cartdim_get_ID,
	LDMS_SHM_MPI_Cart_get_ID,
	LDMS_SHM_MPI_Cart_rank_ID,
	LDMS_SHM_MPI_Cart_coords_ID,
	LDMS_SHM_MPI_Graph_neighbors_count_ID,
	LDMS_SHM_MPI_Graph_neighbors_ID,
	LDMS_SHM_MPI_Cart_shift_ID,
	LDMS_SHM_MPI_Cart_sub_ID,
	LDMS_SHM_MPI_Cart_map_ID,
	LDMS_SHM_MPI_Graph_map_ID,
	LDMS_SHM_MPI_Get_processor_name_ID,
	LDMS_SHM_MPI_Get_version_ID,
	LDMS_SHM_MPI_Get_library_version_ID,
	LDMS_SHM_MPI_Errhandler_create_ID,
	LDMS_SHM_MPI_Errhandler_set_ID,
	LDMS_SHM_MPI_Errhandler_get_ID,
	LDMS_SHM_MPI_Errhandler_free_ID,
	LDMS_SHM_MPI_Error_string_ID,
	LDMS_SHM_MPI_Error_class_ID,
	LDMS_SHM_MPI_Wtime_ID,
	LDMS_SHM_MPI_Wtick_ID,
	LDMS_SHM_MPI_Init_ID,
	LDMS_SHM_MPI_Finalize_ID,
	LDMS_SHM_MPI_Initialized_ID,
	LDMS_SHM_MPI_Abort_ID,
	LDMS_SHM_MPI_Pcontrol_ID,
	LDMS_SHM_MPI_Close_port_ID,
	LDMS_SHM_MPI_Comm_accept_ID,
	LDMS_SHM_MPI_Comm_connect_ID,
	LDMS_SHM_MPI_Comm_disconnect_ID,
	LDMS_SHM_MPI_Comm_get_parent_ID,
	LDMS_SHM_MPI_Comm_join_ID,
	LDMS_SHM_MPI_Lookup_name_ID,
	LDMS_SHM_MPI_Open_port_ID,
	LDMS_SHM_MPI_Publish_name_ID,
	LDMS_SHM_MPI_Unpublish_name_ID,
	LDMS_SHM_MPI_Comm_set_info_ID,
	LDMS_SHM_MPI_Comm_get_info_ID,
	LDMS_SHM_MPI_Accumulate_ID,
	LDMS_SHM_MPI_Get_ID,
	LDMS_SHM_MPI_Put_ID,
	LDMS_SHM_MPI_Win_complete_ID,
	LDMS_SHM_MPI_Win_create_ID,
	LDMS_SHM_MPI_Win_fence_ID,
	LDMS_SHM_MPI_Win_free_ID,
	LDMS_SHM_MPI_Win_get_group_ID,
	LDMS_SHM_MPI_Win_lock_ID,
	LDMS_SHM_MPI_Win_post_ID,
	LDMS_SHM_MPI_Win_start_ID,
	LDMS_SHM_MPI_Win_test_ID,
	LDMS_SHM_MPI_Win_unlock_ID,
	LDMS_SHM_MPI_Win_wait_ID,
	LDMS_SHM_MPI_Win_allocate_ID,
	LDMS_SHM_MPI_Win_allocate_shared_ID,
	LDMS_SHM_MPI_Win_shared_query_ID,
	LDMS_SHM_MPI_Win_create_dynamic_ID,
	LDMS_SHM_MPI_Win_attach_ID,
	LDMS_SHM_MPI_Win_detach_ID,
	LDMS_SHM_MPI_Win_get_info_ID,
	LDMS_SHM_MPI_Win_set_info_ID,
	LDMS_SHM_MPI_Get_accumulate_ID,
	LDMS_SHM_MPI_Fetch_and_op_ID,
	LDMS_SHM_MPI_Compare_and_swap_ID,
	LDMS_SHM_MPI_Rput_ID,
	LDMS_SHM_MPI_Rget_ID,
	LDMS_SHM_MPI_Raccumulate_ID,
	LDMS_SHM_MPI_Rget_accumulate_ID,
	LDMS_SHM_MPI_Win_lock_all_ID,
	LDMS_SHM_MPI_Win_unlock_all_ID,
	LDMS_SHM_MPI_Win_flush_ID,
	LDMS_SHM_MPI_Win_flush_all_ID,
	LDMS_SHM_MPI_Win_flush_local_ID,
	LDMS_SHM_MPI_Win_flush_local_all_ID,
	LDMS_SHM_MPI_Win_sync_ID,
	LDMS_SHM_MPI_Add_error_class_ID,
	LDMS_SHM_MPI_Add_error_code_ID,
	LDMS_SHM_MPI_Add_error_string_ID,
	LDMS_SHM_MPI_Comm_call_errhandler_ID,
	LDMS_SHM_MPI_Comm_create_keyval_ID,
	LDMS_SHM_MPI_Comm_delete_attr_ID,
	LDMS_SHM_MPI_Comm_free_keyval_ID,
	LDMS_SHM_MPI_Comm_get_attr_ID,
	LDMS_SHM_MPI_Comm_get_name_ID,
	LDMS_SHM_MPI_Comm_set_attr_ID,
	LDMS_SHM_MPI_Comm_set_name_ID,
	LDMS_SHM_MPI_File_call_errhandler_ID,
	LDMS_SHM_MPI_Grequest_complete_ID,
	LDMS_SHM_MPI_Grequest_start_ID,
	LDMS_SHM_MPI_Init_thread_ID,
	LDMS_SHM_MPI_Is_thread_main_ID,
	LDMS_SHM_MPI_Query_thread_ID,
	LDMS_SHM_MPI_Status_set_cancelled_ID,
	LDMS_SHM_MPI_Status_set_elements_ID,
	LDMS_SHM_MPI_Type_create_keyval_ID,
	LDMS_SHM_MPI_Type_delete_attr_ID,
	LDMS_SHM_MPI_Type_dup_ID,
	LDMS_SHM_MPI_Type_free_keyval_ID,
	LDMS_SHM_MPI_Type_get_attr_ID,
	LDMS_SHM_MPI_Type_get_contents_ID,
	LDMS_SHM_MPI_Type_get_envelope_ID,
	LDMS_SHM_MPI_Type_get_name_ID,
	LDMS_SHM_MPI_Type_set_attr_ID,
	LDMS_SHM_MPI_Type_set_name_ID,
	LDMS_SHM_MPI_Type_match_size_ID,
	LDMS_SHM_MPI_Win_call_errhandler_ID,
	LDMS_SHM_MPI_Win_create_keyval_ID,
	LDMS_SHM_MPI_Win_delete_attr_ID,
	LDMS_SHM_MPI_Win_free_keyval_ID,
	LDMS_SHM_MPI_Win_get_attr_ID,
	LDMS_SHM_MPI_Win_get_name_ID,
	LDMS_SHM_MPI_Win_set_attr_ID,
	LDMS_SHM_MPI_Win_set_name_ID,
	LDMS_SHM_MPI_Alloc_mem_ID,
	LDMS_SHM_MPI_Comm_create_errhandler_ID,
	LDMS_SHM_MPI_Comm_get_errhandler_ID,
	LDMS_SHM_MPI_Comm_set_errhandler_ID,
	LDMS_SHM_MPI_File_create_errhandler_ID,
	LDMS_SHM_MPI_File_get_errhandler_ID,
	LDMS_SHM_MPI_File_set_errhandler_ID,
	LDMS_SHM_MPI_Finalized_ID,
	LDMS_SHM_MPI_Free_mem_ID,
	LDMS_SHM_MPI_Get_address_ID,
	LDMS_SHM_MPI_Info_create_ID,
	LDMS_SHM_MPI_Info_delete_ID,
	LDMS_SHM_MPI_Info_dup_ID,
	LDMS_SHM_MPI_Info_free_ID,
	LDMS_SHM_MPI_Info_get_ID,
	LDMS_SHM_MPI_Info_get_nkeys_ID,
	LDMS_SHM_MPI_Info_get_nthkey_ID,
	LDMS_SHM_MPI_Info_get_valuelen_ID,
	LDMS_SHM_MPI_Info_set_ID,
	LDMS_SHM_MPI_Pack_external_ID,
	LDMS_SHM_MPI_Pack_external_size_ID,
	LDMS_SHM_MPI_Request_get_status_ID,
	LDMS_SHM_MPI_Type_create_darray_ID,
	LDMS_SHM_MPI_Type_create_hindexed_ID,
	LDMS_SHM_MPI_Type_create_hvector_ID,
	LDMS_SHM_MPI_Type_create_indexed_block_ID,
	LDMS_SHM_MPI_Type_create_hindexed_block_ID,
	LDMS_SHM_MPI_Type_create_resized_ID,
	LDMS_SHM_MPI_Type_create_struct_ID,
	LDMS_SHM_MPI_Type_create_subarray_ID,
	LDMS_SHM_MPI_Type_get_extent_ID,
	LDMS_SHM_MPI_Type_get_true_extent_ID,
	LDMS_SHM_MPI_Unpack_external_ID,
	LDMS_SHM_MPI_Win_create_errhandler_ID,
	LDMS_SHM_MPI_Win_get_errhandler_ID,
	LDMS_SHM_MPI_Win_set_errhandler_ID,
	LDMS_SHM_MPI_Type_create_f90_integer_ID,
	LDMS_SHM_MPI_Type_create_f90_real_ID,
	LDMS_SHM_MPI_Type_create_f90_complex_ID,
	LDMS_SHM_MPI_Reduce_local_ID,
	LDMS_SHM_MPI_Op_commutative_ID,
	LDMS_SHM_MPI_Reduce_scatter_block_ID,
	LDMS_SHM_MPI_Dist_graph_create_adjacent_ID,
	LDMS_SHM_MPI_Dist_graph_create_ID,
	LDMS_SHM_MPI_Dist_graph_neighbors_count_ID,
	LDMS_SHM_MPI_Dist_graph_neighbors_ID,
	LDMS_SHM_MPI_Improbe_ID,
	LDMS_SHM_MPI_Imrecv_ID,
	LDMS_SHM_MPI_Mprobe_ID,
	LDMS_SHM_MPI_Mrecv_ID,
	LDMS_SHM_MPI_Comm_idup_ID,
	LDMS_SHM_MPI_Ibarrier_ID,
	LDMS_SHM_MPI_Ibcast_ID,
	LDMS_SHM_MPI_Igather_ID,
	LDMS_SHM_MPI_Igatherv_ID,
	LDMS_SHM_MPI_Iscatter_ID,
	LDMS_SHM_MPI_Iscatterv_ID,
	LDMS_SHM_MPI_Iallgather_ID,
	LDMS_SHM_MPI_Iallgatherv_ID,
	LDMS_SHM_MPI_Ialltoall_ID,
	LDMS_SHM_MPI_Ialltoallv_ID,
	LDMS_SHM_MPI_Ialltoallw_ID,
	LDMS_SHM_MPI_Ireduce_ID,
	LDMS_SHM_MPI_Iallreduce_ID,
	LDMS_SHM_MPI_Ireduce_scatter_ID,
	LDMS_SHM_MPI_Ireduce_scatter_block_ID,
	LDMS_SHM_MPI_Iscan_ID,
	LDMS_SHM_MPI_Iexscan_ID,
	LDMS_SHM_MPI_Ineighbor_allgather_ID,
	LDMS_SHM_MPI_Ineighbor_allgatherv_ID,
	LDMS_SHM_MPI_Ineighbor_alltoall_ID,
	LDMS_SHM_MPI_Ineighbor_alltoallv_ID,
	LDMS_SHM_MPI_Ineighbor_alltoallw_ID,
	LDMS_SHM_MPI_Neighbor_allgather_ID,
	LDMS_SHM_MPI_Neighbor_allgatherv_ID,
	LDMS_SHM_MPI_Neighbor_alltoall_ID,
	LDMS_SHM_MPI_Neighbor_alltoallv_ID,
	LDMS_SHM_MPI_Neighbor_alltoallw_ID,
	LDMS_SHM_MPI_Comm_split_type_ID,
	LDMS_SHM_MPI_Get_elements_x_ID,
	LDMS_SHM_MPI_Status_set_elements_x_ID,
	LDMS_SHM_MPI_Type_get_extent_x_ID,
	LDMS_SHM_MPI_Type_get_true_extent_x_ID,
	LDMS_SHM_MPI_Type_size_x_ID,
	LDMS_SHM_MPI_Comm_create_group_ID,
	LDMS_SHM_MPI_File_open_ID,
	LDMS_SHM_MPI_File_close_ID,
	LDMS_SHM_MPI_File_delete_ID,
	LDMS_SHM_MPI_File_set_size_ID,
	LDMS_SHM_MPI_File_preallocate_ID,
	LDMS_SHM_MPI_File_get_size_ID,
	LDMS_SHM_MPI_File_get_group_ID,
	LDMS_SHM_MPI_File_get_amode_ID,
	LDMS_SHM_MPI_File_set_info_ID,
	LDMS_SHM_MPI_File_get_info_ID,
	LDMS_SHM_MPI_File_set_view_ID,
	LDMS_SHM_MPI_File_get_view_ID,
	LDMS_SHM_MPI_File_read_at_ID,
	LDMS_SHM_MPI_File_read_at_all_ID,
	LDMS_SHM_MPI_File_write_at_ID,
	LDMS_SHM_MPI_File_write_at_all_ID,
	LDMS_SHM_MPI_File_iread_at_ID,
	LDMS_SHM_MPI_File_iwrite_at_ID,
	LDMS_SHM_MPI_File_read_ID,
	LDMS_SHM_MPI_File_read_all_ID,
	LDMS_SHM_MPI_File_write_ID,
	LDMS_SHM_MPI_File_write_all_ID,
	LDMS_SHM_MPI_File_iread_ID,
	LDMS_SHM_MPI_File_iwrite_ID,
	LDMS_SHM_MPI_File_seek_ID,
	LDMS_SHM_MPI_File_get_position_ID,
	LDMS_SHM_MPI_File_get_byte_offset_ID,
	LDMS_SHM_MPI_File_read_shared_ID,
	LDMS_SHM_MPI_File_write_shared_ID,
	LDMS_SHM_MPI_File_iread_shared_ID,
	LDMS_SHM_MPI_File_iwrite_shared_ID,
	LDMS_SHM_MPI_File_read_ordered_ID,
	LDMS_SHM_MPI_File_write_ordered_ID,
	LDMS_SHM_MPI_File_seek_shared_ID,
	LDMS_SHM_MPI_File_get_position_shared_ID,
	LDMS_SHM_MPI_File_read_at_all_begin_ID,
	LDMS_SHM_MPI_File_read_at_all_end_ID,
	LDMS_SHM_MPI_File_write_at_all_begin_ID,
	LDMS_SHM_MPI_File_write_at_all_end_ID,
	LDMS_SHM_MPI_File_read_all_begin_ID,
	LDMS_SHM_MPI_File_read_all_end_ID,
	LDMS_SHM_MPI_File_write_all_begin_ID,
	LDMS_SHM_MPI_File_write_all_end_ID,
	LDMS_SHM_MPI_File_read_ordered_begin_ID,
	LDMS_SHM_MPI_File_read_ordered_end_ID,
	LDMS_SHM_MPI_File_write_ordered_begin_ID,
	LDMS_SHM_MPI_File_write_ordered_end_ID,
	LDMS_SHM_MPI_File_get_type_extent_ID,
	LDMS_SHM_MPI_Register_datarep_ID,
	LDMS_SHM_MPI_File_set_atomicity_ID,
	LDMS_SHM_MPI_File_get_atomicity_ID,
	LDMS_SHM_MPI_File_sync_ID,
	LDMS_SHM_MPI_Aint_add_ID,
	LDMS_SHM_MPI_Aint_diff_ID,
	LDMS_SHM_MPI_File_iread_all_ID,
	LDMS_SHM_MPI_File_iread_at_all_ID,
	LDMS_SHM_MPI_File_iwrite_all_ID,
	LDMS_SHM_MPI_File_iwrite_at_all_ID,
	LDMS_SHM_MPI_NUM_FUNCTIONS
} ldms_shm_MPI_func_id_t; /* Enumeration for creating a unique mapping  for MPI functions *//* TODO create this using the generator */

/**
 * \brief find the function id represents the function name
 *
 * \param func_name Name of the MPI function
 * \return non-negative func_id if the MPI function name is found, -1 otherwise
 */
ldms_shm_MPI_func_id_t find_func_id(char* func_name); /* TODO use str_map for this */
/**
 * initialize the MPI function names for base events
 */
void ldms_shm_mpi_init_func_names(); /* TODO create this using the generator */

#endif /* MPI_PROFILER_FUNC_LIST_H */
