.\" Manpage for ldms_rdc_sampler_schema_name
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 1 "2 April 2021" "v4.4" "LDMS utility ldms_rdc_sampler_schema_name man page"

.SH NAME
ldms_rdc_schema_name - man page for the LDMS rdc_sampler plugin support utility

.SH SYNOPSIS
ldms_rdc_schema_name -h
ldms_rdc_schema_name <plugin config options>

.SH DESCRIPTION
The rdc_sampler plugin generates a schema name including a hash of certain
configuration data. ldms_rdc_schema_name provides the user with the
resulting name before running ldmsd so that store plugins can be configured.

.SH CONFIGURATION ATTRIBUTE SYNTAX

See Plugin_rdc_sampler(7).

.SH EXAMPLES
.PP
.nf
#ldms_rdc_schema_name -h
<dump of the usage details from the plugin.>

# ldms_rdc_schema_name metrics=base schema=myrdc_sampler shape=0 | grep -v ERROR
myrdc_sampler_2_51dcba58

# ldms_rdc_schema_name metrics=xgmi shape=1
rdc_sampler_device_e3e41d59
.fi

.SH NOTES
The rdc libraries loaded by the plugin and the program may emit inconsequential error messages to stdout.
One such begins with "<timestamp> ERROR RdcLibraryLoader.cc".

.SH SEE ALSO
Plugin_rdc_sampler(7)
