.\" Manpage for Plugin_rdc_sampler
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "1 Apr 2021" "v4.3" "LDMS Plugin rdc_sampler man page"

.SH NAME
Plugin_rdc_sampler - man page for the LDMS rdc_sampler plugin

.SH SYNOPSIS
Within ldmsd_controller or a configuration file:
.br
config name=rdc_sampler [ <attr>=<value> ]

.SH DESCRIPTION
The rdc_sampler plugin provides AMD gpu device data. Data sets may be wide or per-device.
Plugins for the ldmsd (ldms daemon) are configured via ldmsd_controller
or a configuration file.

.SH CONFIGURATION ATTRIBUTE SYNTAX

.TP
.BR config
name=<plugin_name> [producer=<name>] [instance=<name>] [component_id=<uint64_t>]
[schema=<name_base>] [uid=<user-id>] [gid=<group-id>] [perm=<mode_t permission bits>]
[metrics=LIST] [update_freq=MICROSEC] [max_keep_age=SEC] [max_keep_samples=N]
.br
configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be rdc_sampler.
.TP
producer=<pname>.
.br
The producer string value for the timing set.
.TP
instance=<set_prefix>
.br
The set instance names will be suffixed by device number (gpu%d).
.TP
schema=<name_base>
.br
Optional schema base name. The default is rdc_sampler. The name base is suffixed
to create uniquely defined schema names based on the plugin options specified.
.TP
component_id=<compid>
.br
Optional component identifier for the timing set. Defaults to zero.
.TP
metrics=LIST
.br
The list of values to be collected as named in rdc_field_t from rdc/rdc.h.
.TP
update_freq=MICROSEC
.br
An argument passed to rdc_field_watch.
.TP
max_keep_age=SEC
.br
An argument passed to rdc_field_watch.
.TP
max_keep_samples=N
.br
An argument passed to rdc_field_watch.
.TP
warmup=K
.br
Delay K cycles update_freq long before attempting to read data from the gpu.
.RE

.SH EXAMPLES
.PP
Within ldmsd_controller or a configuration file:
.nf
load name=rdc_sampler
config name=rdc_sampler component_id=1
start name=rdc_sampler interval=1000000
.fi

.SH NOTES
The exact schema name that will be generated can be determined using the ldms_rdc_schema_name utility. The data available may depend on the specific GPUs and their configuration.

The rdc libraries loaded by the plugin may emit inconsequential error messages to stdout.
Two such begin with
 "<timestamp> ERROR RdcLibraryLoader.cc"
 "<timestamp> ERROR RdcMetricFetcherImpl.cc"
The latter suggests you may have requested metrics unsupported by your hardware.

.SH BUGS
At ldmsd exit, there is a race between sampler termination and the rdc library thread cleanup.
This may lead to an exception being thrown in the library code that terminates ldmsd with a C++ exception message.

.SH SEE ALSO
ldmsd(8), ldms_quickstart(7), ldmsd_controller(8), ldms_rdc_schema_name(1)
