.\" Manpage for Plugin_my_plugin
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "26 Sep 2019" "v4" "LDMS Plugin my_plugin man page"

.SH NAME
Plugin_my_plugin - man page for the LDMS my_plugin plugin

.SH SYNOPSIS
Within ldmsd_controller or a configuration file:
.br
config name=my_plugin [ <attr>=<value> ]

.SH DESCRIPTION
With LDMS (Lightweight Distributed Metric Service), plugins for the ldmsd (ldms daemon) are configured via ldmsd_controller
or a configuration file. The my_plugin plugin provides a ticker, like the clock plugin.

.SH CONFIGURATION ATTRIBUTE SYNTAX
The my_plugin plugin uses the sampler_base base class. This man page covers only the configuration attributes, or those with default values, specific to the this plugin; see ldms_sampler_base.man for the attributes of the base class.


.TP
.BR config
name=<plugin_name> [schema=<sname>]
.br
configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be my_plugin.
.TP
schema=<schema>
.br
Optional schema name.
.RE

.SH BUGS
No known bugs.

.SH EXAMPLES
.PP
Within ldmsd_controller or a configuration file:
.nf
load name=my_plugin
config name=my_plugin producer=vm1_1 instance=vm1_1/my_plugin
start name=my_plugin interval=1000000
.fi

.SH SEE ALSO
ldmsd(8), ldms_quickstart(7), ldmsd_controller(8), ldms_sampler_base(7)
