.\" Manpage for Plugin_kgnilnd
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "11 Sep 2014" "1.2" "LDMS Plugin kgnilnd man page"

.SH NAME
Plugin_kgnilnd - man page for the LDMS kgnilnd plugin

.SH SYNOPSIS
Within ldmsctl
.br
ldmsctl> config name=kgnilnd [ <attr>=<value> ]

.SH DESCRIPTION
With LDMS (Lightweight Distributed Metric Service), plugins for the ldmsd (ldms daemon) are configured via ldmsctl.
The kgnilnd plugin provides Cray specific info from /proc/kgnilnd.

.SH LDMSCTL CONFIGURATION ATTRIBUTE SYNTAX

.TP
.BR config
name=<plugin_name> component_id=<comp_id> set=<set_name>
.br
ldmsctl configuration line
.RS
.TP
name=<plugin_name>
.br
This MUST be kgnilnd.
.TP
component_id=<comp_id>
.br
The component id numerical value.
.TP
set=<set_name>
.br
The name of the metric set.
.RE

.SH BUGS
No known bugs.

.SH EXAMPLES
.nf
$/tmp/opt/ovis/sbin/ldmsctl -S /var/run/ldmsd/metric_socket_vm1_1
ldmsctl> load name=kgnilnd
ldmsctl> config name=kgnilnd component_id=1 set=vm1_1/kgnilnd
ldmsctl> start name=kgnilnd interval=1000000
ldmsctl> quit
.fi

.SH SEE ALSO
LDMS_Authentication(7), ldmsctl(1), ldmsd(1), ldms_ls(1),
Plugin_cray_system_sampler_variants(7), Plugin_lustre2_client(7), Plugin_meminfo(7), Plugin_procnetdev(7), Plugin_procnfs(7),
Plugin_procsensors(7), Plugin_store_csv(7), Plugin_store_derived_csv(7), Plugin_sysclassib(7), Plugin_procstatutil(7), Plugin_vmstat(7)
