#!/bin/sh
./autogen.sh
./configure '--enable-ssl' '--enable-rdma' '--disable-zap' '--disable-zaptest' '--disable-rpath' '--enable-authentication' '--disable-readline' '--enable-sysclassib' 'CC=gcc' 'CXX=g++' --disable-sos --enable-libgenders
./util/release_tarball-240.sh
cd Release
tar zxf ldms-2.4.7.tar.gz
cd ldms-2.4.7
./configure '--enable-ssl' '--enable-rdma' '--disable-zap' '--disable-zaptest' '--disable-rpath' '--enable-authentication' '--disable-readline' '--enable-sysclassib' 'CC=gcc' 'CXX=g++' --disable-sos --enable-libgenders
make toss3
