#!/bin/sh
./autogen.sh
./configure '--enable-ssl' '--with-libevent=/usr/lib64/ovis-libevent2' '--disable-rpath' '--disable-readline' 'CC=gcc' 'CXX=g++' --enable-sos --enable-baler --enable-swig --enable-doc --enable-doc-html --with-pkglibdir=ovis-ldms
mkdir -p Release
rm -rf Release/*
./util/release_tarball-300-mon6.sh
cd Release
echo "============================= bundle done ============="
tar zxf ldms-3.0.0.tar.gz
cd ldms-3.0.0
echo "============================= configure for mon6 rpms ============="
./configure '--enable-ssl' '--with-libevent=/usr/lib64/ovis-libevent2' '--disable-rpath' '--disable-readline' 'CC=gcc' 'CXX=g++' --enable-sos --enable-baler --enable-swig --enable-doc --enable-doc-html --with-pkglibdir=ovis-ldms
echo "============================= make mon6 rpms ============="
make lanl-mon6
