#!/bin/sh
./autogen.sh
./configure '--enable-ssl' '--enable-rdma' '--enable-ncsa-unified' '--disable-zap' '--disable-zaptest' '--with-libevent=/usr/lib64/ovis-libevent2' '--disable-rpath' '--enable-authentication' '--disable-readline' 'CC=gcc46' 'CXX=g++' --disable-sos 
./util/release_tarball-240.sh
cd Release
tar zxf ldms-2.4.0.tar.gz
cd ldms-2.4.0
./configure '--enable-ssl' '--enable-rdma' '--enable-ncsa-unified' '--disable-zap' '--disable-zaptest' '--with-libevent=/usr/lib64/ovis-libevent2' '--disable-rpath' '--enable-authentication' '--disable-readline' 'CC=gcc46' 'CXX=g++' --disable-sos 
make toss
