#!/bin/sh
./autogen.sh
./configure '--enable-ssl' '--enable-rdma' '--enable-ncsa-unified' '--disable-zap' '--disable-zaptest' '--with-libevent=/usr/lib64/ovis-libevent2' '--disable-rpath' '--enable-authentication' '--disable-readline' '--enable-sysclassib' 'CC=gcc' 'CXX=g++' --disable-sos --enable-libgenders
./util/release_tarball-240.sh
cd Release
tar zxf ldms-2.4.5.tar.gz
cd ldms-2.4.5
./configure '--enable-ssl' '--enable-rdma' '--enable-ncsa-unified' '--disable-zap' '--disable-zaptest' '--with-libevent=/usr/lib64/ovis-libevent2' '--disable-rpath' '--enable-authentication' '--disable-readline' '--enable-sysclassib' 'CC=gcc' 'CXX=g++' --disable-sos --enable-libgenders
make toss
